elastic/synthetics

__tests__/reporters/json.test.ts
src/reporters/json.ts

+ Keeps the version intact in tests to not break for every release. 
Check the snapshot here for details  - https://github.com/elastic/synthetics/blob/a276de731d0f000ca564c6a64b97d023c780004a/__tests__/reporters/__snapshots__/json.test.ts.snap#L4

fix: mock pkg version in json reporter

---

__tests__/index.test.ts
src/core/runner.ts
src/index.ts

+ fix #113 
+ It ensures if the current run is active, we don't schedule new runs even invoked via CLI or another programmatic run

fix: ensure we execute tests only once per run

---

__tests__/core/runner.test.ts
__tests__/reporters/base.test.ts
__tests__/reporters/json.test.ts
src/core/runner.ts
src/reporters/json.ts

+ fix #118 
+ Timestamps are calculated for every event when the JSON is written to the FD for most of the events as we want the intermediately steps like `network`, `screenshot`, `filmstrips` timestamps to fall under their respective steps timestamps and does not extend beyond that. 
+ Way to test this works
```
node dist/cli.js examples/todos/basics.journey.ts -j --metrics --screenshots | jq '{t: .type, ts: .["@timestamp"]}'
```
We would still use the `start`  and `end` timings for other calculations which is based on the monotonic clock based on the devtools protocol.

fix: generate timestamps when events are reported

---

Dockerfile
build-docker.sh
examples/docker/bash-build-local.sh
examples/docker/bash.sh
examples/docker/heartbeat.docker.yml
examples/docker/run.sh
examples/todos/add-remove.journey.ts
examples/todos/basics.journey.ts
examples/todos/helpers.ts
examples/todos/package.json
package.json
src/cli.ts
src/core/index.ts
src/helpers.ts
src/parse_args.ts

+ fix #124 #123 
This PR fixes multiple issues 
+ Handle symlinks and ignore them while running suites as it would crash the process by recursively searching for the same files
+ Ignore `node_modules` by default when running journey
+ Always install the latest version of synthetics package on the docker image and invoke from heartbeat side using `elastic-synthetics` executable without using the `npx` command as it would resolve the problem with local/global package collision
+ TS files are only compiled on the fly without type checking which is slower and not required for journey files from the users.
+ `rm -rf node_modules`
+ `npm unlink` if you have linking before
+ `npm install` on the root folder
+ `cd examples/todos/ && npm install` 
+ `node dist/cli.js examples/todos` in the root or …

fix: handle symlinks and make examples work

---

Dockerfile

This fixes the issue with broken NPM tags, where we'd publish the oldest alpha as latest.

Install alpha by default

---

src/core/runner.ts
src/reporters/base.ts

+ fix #110 
+ runner end should be called after reset since we are logging the output inside reset
+ Moved from `nextTick` to `setTimeout` as its called after all the micro tasks and ensure all log statements are printed before we end stream.

fix: close fd after debug logs are written

---

examples/docker/bash.sh

Simple mistake in the bash script made it ignore the version arg

Correction parse arg version for docker/bash.sh

---

__tests__/core/runner.test.ts
src/core/runner.ts

Prior to this patch we'd only report the URL in JSON output when the step passed.

Report URL on errors

---

examples/todos/README.md
examples/todos/package.json

+ Uses the published versions in examples to make sure the examples works out of the box without doing local builds. 
+ updated readme.md with steps to run.

chore: use published version in examples

---

examples/todos/README.md
package.json
src/parse_args.ts

+ this should make the `npx @elastic/synthetics` work. We have decided to keep the executable available under two names. We will revisit during the beta phase

chore: publish under two names

---

__tests__/helper.test.ts
src/cli.ts
src/helpers.ts
src/reporters/base.ts

+ fix #88
+ Introduce a rewrite stack function that rewrites the playwright specific logs message and strips them to only two adjacent lines to keep the error meaningful instead of giving repetitive lines on every retries.
+ Also removed the message field from error as it contains the same repetetive message from the error stack. UI can only show stacktrace and skip showing errors.

fix: rewrite playwright logs from errors

---

Dockerfile

Without this chrome zombies sometimes appear. We should use an init daemon since we spawn subprocesses.
Dockerfile change copied from https://github.com/krallin/tini#using-tini

Use tini init daemon in Docker

---

Dockerfile

Without this chrome zombies sometimes appear. We should use an init daemon since we spawn subprocesses.
This is a redo of #134 which was reverted due to a bug. This should be tested with `./run-build-local.sh` and .`./bash-build-local.sh` (you can run `ps` in bash to check for `tini`)

Use tini init daemon (correctly) in Docker (#134)

---

examples/todos/package.json

This dep wasn't bumped with the last release. In the future we should automate this

Bump todos dep to use alpha6

---

__tests__/index.test.ts
src/core/gatherer.ts
src/core/runner.ts
src/index.ts
src/parse_args.ts

+ fix #143 
+ Use `filmstrips` view for capturing the screenshot trace events instead of using the `screenshot` event, This should speed up the run from heartbeat side.

fix: use filmstrips option for capturing trace

---

package-lock.json
package.json

+ Allows running playwright on macOS Big Sur. Fails to launch browsers on older versions.

chore: update playwright to 1.6.2

---

Dockerfile
build-docker.sh
examples/todos/package.json
package.json

+ fix #142 
+ Forcefully reinstalls our `@elastic/synthetics` package by ignoring the cache incase any versions have changed. We have not used the `docker build --no-cache` as it will also clear out other dependency caches
+ By having the latest version on both official docker image and examples pointing to the latest published version. We synchronise the playwright versions inside the docker image and do not have a broken state. 
+ We can also remove the intermin solution that is put inside the heartbeat code https://github.com/elastic/beats/blob/heartbeat-synthetics/x-pack/heartbeat/monitors/browser/synthexec/synthexec.go#L57 as the problem is not related to playwright being available instead a broken state.  
Steps to test this flow. 
```sh
// remove the previous docker image if you …
```

fix: sync browser version in docker and examples

---

package-lock.json
package.json
src/browser-service.ts
src/core/gatherer.ts
src/core/runner.ts
src/index.ts
src/parse_args.ts

This PR adds a browser service that can be used to launch browser on demand. It also adds `--ws-endpoint` option for the cli.
- To run the browser service simply run the JS file: `node dist/browser-service.js`
- To point the tests to use the browser service: `node dist/cli.js examples/todos/ --ws-endpoint=ws://localhost:9322`

feat: add browser service to launch browsers

---

.ci/Jenkinsfile
__tests__/e2e/docker-compose.yml
__tests__/e2e/scripts/setup.sh
__tests__/e2e/scripts/test.sh

It adds a stage to run the e2e teste

ci: run e2e tests

---

package.json

+ This is a follow up of #142 and allows us to control the update of playwright effectively browsers to tie it with the proper version. Having `^` or `~` would allow minor/patch versions to be installed on user's machine/test environments if lockfiles are not taken in to account.

chore: disallow auto update of chrome browser

---

__tests__/plugins/tracing.test.ts
src/plugins/tracing.ts

+ Changes the Tracing.start protocol command to use the `ReportEvents` instead of `ReturnAsStream`. This makes the trace gathering much faster, as observed in some automated run timings:
Before - 3 seconds 
After -  2.5 seconds 
This would be useful as we add more categories to trace when we start doing this #120

chore: improve tracer time by consuming as events

---

__tests__/plugins/browser-console.test.ts
src/common_types.ts
src/core/runner.ts
src/plugins/browser-console.ts
src/plugins/network.ts
src/plugins/plugin-manager.ts
src/reporters/json.ts

+ part of #152 
+ Associate the network information with each step as its required for the waterfall chart creation
+ fix the timestamp information as it was pointing to the journey end timestamp as opposed to the step start/end timestamp
+ Move `start/end` in favor of `requestSentTime/loadEndTime` as its when events are written and not the actual duration. 
/cc @Kerry350

fix: associate network info with each step

---

__tests__/helper.test.ts
__tests__/plugins/tracing.test.ts
__tests__/reporters/__snapshots__/json.test.ts.snap
__tests__/reporters/json.test.ts
src/common_types.ts
src/helpers.ts
src/plugins/tracing.ts
src/reporters/json.ts

+ Part of #85 
+ converts the trace timestamp used by the chrome devtools trace event format to the internally used monotonic clock which is based on the network events and also used on journey and step start/end timings.
+ This makes querying for filmstrips for each step easier as we can directly query for all `journey/filmstrip` events within the `start` and `end` time of the step.

feat: adjust trace timestamps with internal clock

---

Dockerfile

As part of bringing synthetics to beta we want to merge the special heatbeat branch to master. We still, however, want to restrict synthetics usage to the synthetics docker image to prevent users from getting confusing errors running synthetics on a plain system. This env var can be checked by heartbeat before activating any synthetics monitors.
Goes toward #140

Add synthetics capabilities env var to Dockerfile

---

Dockerfile

The env declaration must happen after `FROM`

Fix misordered env declaration in dockerfile

---

__tests__/plugins/network.test.ts
src/common_types.ts
src/plugins/network.ts

+ fix #166 
+ part of #152 
+ Adds the request timing calculations for all network events when `--network` flag is enabled. The output is expected to be in the format
```
{
blocked: 0.8809999562799931,
queueing: 0.49599993508309126,
proxy: -1,
dns: -1,
ssl: -1,
connect: -1,
send: 0.1300000585615635,
wait: 60.22300000768155,
receive: 0.9560000617057085,
total: 62.686000019311905
}
```
**All of the data is in `milliseconds` and any missing data will be denoted with `-1`**

feat: add request timing calculation for waterfall

---

Dockerfile

I cannot run `docker build .` as there are `\\` in the Dockerfile instead of `\`. Not sure if this is on purpose or not?

Fix Dockerfile by removing slashes

---

__tests__/plugins/network.test.ts
src/plugins/network.ts
utils/server.ts

+ fix #175 
+ Redirected requests have the same `requestId` which was overriding the original request with the redirected request. As a result the redirected requests was simply not shown in the waterfall. 
+ The solution is to check if the request is issued with the same `requestId` and simply mimic the usual flow from `requestSent` -> `responseReceived` -> `LoadingFinished` by using the redirected response which is available as part of the `event.redirectedResponse` data. 
Check the below events for a sample website which goes from HTTP -> HTTPS and how 301 works. 
```json
{"type":"journey/network_info","@timestamp":1609895099415610.8,"journey":{"name":"check that title is present","id":"check that title is present"},"step":{"name":"go to app","index":1},"payload":{"step":{"name":"go to …
```

fix: capture redirected requests in waterfall

---

src/cli.ts
src/index.ts

+ fix #172 
+ Moved the source map support during run time instead of import time.

fix: transpile suites to latest target

---

__tests__/plugins/network.test.ts
src/plugins/network.ts

+ Blocking time was set to `Infinity` when timing data was unavailable. Found it while adding tests, I have added more descriptive tests for timing calculation. 
+ fix #185

fix: calculate blocking time properly for missing timing data

---

examples/docker/run.sh

This was broken in https://github.com/elastic/synthetics/pull/189 which quoted this variable that should not have been quoted

Fix broken overwrite of heartbeat args

---

__tests__/cli.test.ts
__tests__/e2e/uptime.journey.ts
__tests__/fixtures/error.journey.ts
__tests__/fixtures/fake.journey.ts
__tests__/index.test.ts
jest.config.js
src/cli.ts
src/index.ts

+ fix #191 
+ Handle the exit code from the CLI runs correctly, now we exit with >0 error codes when any of the journey fails which include steps as well. If any error is thrown via assertion or error - CLI will exit with 1 exit code
+ Added tests by creating a CLI mock that runs and waits for the exit code.
+ Cleaned up some unwanted CLI args parsing code which is not relevant for our run API.

fix: handle exit code correctly

---

package.json
src/cli.ts
src/common_types.ts
src/parse_args.ts

+ Updated the required deps-> mostly for playwright newer versions
+ Fixed the types mismatch for CLIArgs
+ Got rid of the parse args function and getting it ready for the new commands like `record`, `perf`, etc.

chore: upgrade deps and fix types

---

__tests__/fixtures/networkinfo.ts
__tests__/reporters/__snapshots__/json.test.ts.snap
__tests__/reporters/json.test.ts
src/common_types.ts
src/core/runner.ts
src/plugins/network.ts
src/reporters/json.ts

+ fix #164 
+ All ecs related field are nested under `root_fields` as discussed.

feat: move fields to ECS format

---

.ci/Jenkinsfile
CONTRIBUTING.md

Release automation from the `master` branch, with the below support:
* UI based, so it's required to be login in the CI and trigger a build manually with the `release` parameter.
* Email/slack notifications when a new release is triggered.
* Input approval to confirm the release should be out with 12 hours waiting for.
* Release automation with 2FA.
In addition, I updated the docs regarding the release process with the CI.
Closes https://github.com/elastic/synthetics/issues/107
* For such I used a new repo (https://github.com/v1v/test-2fa/tree/feature/synthetics) that contains these changes.
* https://preview.npmjs.com/package/test-2fa is the package
* See releases in https://preview.npmjs.com/package/test-2fa/v/0.0.1-alpha.13
The release process might look like the below …

[CI] Automate release process

---

src/core/runner.ts

+ Wait for the load event only when screenshots flag is enabled. 
+ waiting for the load event for normal scenarios is unnecessary and `screenshots`

refactor: wait till load when screenshot is enabled

---

__tests__/core/browser-service.test.ts
__tests__/core/gatherer.test.ts
__tests__/index.test.ts
__tests__/plugins/browser-console.test.ts
__tests__/plugins/network.test.ts
__tests__/plugins/performance.test.ts
__tests__/plugins/tracing.test.ts
src/core/gatherer.ts
src/core/runner.ts
src/index.ts
src/parse_args.ts

+ fix #225
+ By default the chromium sanboxing is disabled and can be enabled with `--sandbox` CLI option or using our runner API.
+ Cleaned up the driver arguments. 
```ts
import { run } from "@elastic/synthetics";
await run({ sandbox: true })
```

fix: disable chromium sandboxing by default

---

__tests__/e2e/docker-compose.yml
__tests__/e2e/scripts/setup.sh
__tests__/e2e/uptime.journey.ts
examples/todos/package.json

While doing poc e2e tests were setup using 7.10.0 , since we have 8.0.0-SNAPSHOT available, we should run tests against that version.
Also using 5620 and 9220 ports for kibana and ES. Since 5601 and 9200 are being used for local dev usually.
Fixes: https://github.com/elastic/synthetics/issues/197

Use 8.0.0-SNAPSHOT to run e2e tests

---

.ci/Jenkinsfile
.gitignore
__tests__/e2e/docker-compose.yml
__tests__/e2e/scripts/setup.sh
__tests__/e2e/scripts/test.sh
__tests__/e2e/uptime.journey.ts
__tests__/reporters/__snapshots__/junit.test.ts.snap
__tests__/reporters/junit.test.ts
src/cli.ts
src/common_types.ts
src/core/runner.ts
src/parse_args.ts
src/reporters/base.ts
src/reporters/index.ts
src/reporters/junit.ts

+ fix #149 
+ Can be invoked via the `reporter flag` from CLI
```sh
npx @elastic/synthetics suites --reporter=junit
// OR
npx @elastic/synthetics suites --reporter junit
```
```xml
<testsuites name=\\"\\" tests=\\"2\\" failures=\\"1\\" skipped=\\"1\\" errors=\\"0\\" time=\\"0\\">
<testsuite name=\\"j1\\" tests=\\"2\\" failures=\\"1\\" skipped=\\"1\\" errors=\\"0\\">
<testcase name=\\"s1\\" classname=\\"j1 s1\\" time=\\"1\\">
<failure message=\\"Boom\\" type=\\"Error\\">
Error: Boom
</failure>
</testcase>
<testcase name=\\"s2\\" classname=\\"j1 s2\\" time=\\"1\\">
<skipped message=\\"previous step failed\\">
</skipped>
</testcase>
</testsuite>
</testsuites>
```
+ Extract the test case to a separate file using the env flag
```
SYNTHETICS_JUNIT_FILE='/path/to/junit.xml' npx …
```

feat: add junit reporter

---

.ci/Jenkinsfile

Spin up a new CI agent for the release stage
Reusing an existing workspace causes permission issues
```
/var/lib/jenkins/workspace/nt-rum_elastic-synthetics_master/src/github.com/elastic/synthetics/examples/todos/node_modules: Operation not permitted
```

ci: provision agent for the release stage

---

examples/todos/advanced.journey.ts
examples/todos/basic.journey.ts
examples/todos/helpers.ts
examples/todos/package.json
src/index.ts

+ Solves the problem specified in #158
+ Exposes all of the driver types that could be used from the suites
+ It solves the problem of users needing to import `playwright-core` or `playwright-*` for using types and eventually run in to problems of version mismatch. 
+ Once we add support for multiple browsers, we would expose the types from `playwright-core` instead and rest would look the same

feat: expose driver types from the agent

---

examples/todos/package.json

+ The new release is published with the types- we can safely use it now to refer types. https://github.com/elastic/synthetics/releases/tag/v0.0.1-alpha.11

chore: fix todos example deps

---

.ci/Jenkinsfile

Set `VERSION` with the upcoming new release
In my local I had some notice traces when running the command `npm version prerelease --preid=alpha`
Will this cause any issues? 
Is there any other command in npm to fetch the new version?
Closes https://github.com/elastic/synthetics/issues/240

ci: set the correct new version

---

__tests__/reporters/__snapshots__/json.test.ts.snap
__tests__/reporters/json.test.ts
src/reporters/json.ts

+ Reports the number of journeys as `synthetics/metadata` event which would be potentially used in the `--dry-run` command which reports this event as well registered journeys via `journey/register` command. 
Dry run in todos basic example 
```
{"type":"synthetics/metadata","@timestamp":1616806791018720,"root_fields":{"num_journeys":2,"os":{"platform":"darwin"},"package":{"name":"@elastic/synthetics","version":"0.0.1-alpha.11"}},"package_version":"0.0.1-alpha.11"}
{"type":"journey/register","@timestamp":1616806791019158,"journey":{"name":"check if title is present","id":"check if title is present"},"root_fields":{"os":{"platform":"darwin"},"package":{"name":"@elastic/synthetics","version":"0.0.1-alpha.11"}},"package_version":"0.0.1-alpha.11"} …
```

feat: report number of journeys in json

---

__tests__/plugins/network.test.ts
src/plugins/network.ts

+ fix #246 #190
+ We now properly calculate the request timings 
- When the remote host connection cannot be made (Network failure)
- When the response is never received for a given request
- When the request in inflight is aborted 
+ Added test cases for all the scenarios and tested the confirmed the timing with chrome devtools. 
When the request is  queued and the request got aborted due to browser being explicited closed or the connection cannot be established - The timing data point would look like this explaining that the given request is stalled / blocked for the whole time frame. 
```
{
blocked: 2.885,
queueing: -1,
proxy: -1,
dns: -1,
ssl: -1,
connect: -1,
send: -1,
wait: -1,
receive: -1,
total: 2.885
}
```
Matching chrome devtools behaviour

fix: handle aborted/inflight network requests

---

__tests__/fixtures/networkinfo.ts
__tests__/reporters/__snapshots__/json.test.ts.snap
__tests__/reporters/json.test.ts
src/reporters/json.ts

+ fix #248 
+ This PR removes duplicate fields from the network timing data, all ecs compatible fields are moved to `root_fields` which heartbeat writes to the top level document and rest are inside `payload` which does not get any special treatment.

feat: remove duplicate payload fields

---

__tests__/core/runner.test.ts
src/core/runner.ts
src/index.ts
src/reporters/base.ts
src/reporters/reporter.ts

In order to support getting access to runner events from the standard `run()` API I think it would be good to support custom `Runner` classes. This PR adds support for a `Runner` class being passed as the `reporter` option, `new`s up this class when the runner starts, and passes the `Runner` instance as well as the `ReporterOptions` to the constructor, and then moves on.

add support for custom reporters

---

examples/todos/Dockerfile

Thanks to @a03nikki for figuring this one out. Here, we add an example of adding custom certs to the synthetics container image.

Document adding CAs in offline example

---

__tests__/core/browser-service.test.ts
__tests__/core/gatherer.test.ts
__tests__/core/runner.test.ts
__tests__/plugins/browser-console.test.ts
__tests__/plugins/network.test.ts
__tests__/plugins/performance.test.ts
__tests__/plugins/tracing.test.ts
src/core/gatherer.ts
src/core/runner.ts

+ This PR improves the test execution time when there are multiple journeys involved while running the test suites. Previously  we relied on spawning browser instance for every journey execution which is not required as context already provides enough isolation and each context is fresh (does not share any state or cache) used for each journey runs
+ This removes the time that is required for spawning browser for each run which is in order of ~100ms. 
1. For todos directory with 4 journeys
```
Before - 3600ms
After - 2400ms
```
2. Custom with increased number of journeys to showcase the impact.
```
// 20 journeys
Before - 11200ms
After - 5800ms
// 50 journeys
Before - 28700ms
After - 14800ms
```

perf: use context isolation for inidividual journeys

---

package-lock.json
package.json

Our `package-lock.json` Is a bit out of date and there are some security issues in lodash that are being automatically detected by github even though they don't apply to us. Any lodash issue do not apply because they would only affect developers in the compilation phase and we already run plenty of arbitrary code.
That said it's good to keep our dependencies up to date and this PR accomplishes that.
this PR also bumps us to playwright version 1.11.0

Upgrade all deps 

---

__tests__/reporters/__snapshots__/base.test.ts.snap
__tests__/reporters/base.test.ts
src/reporters/base.ts

+ When there are errors thrown in any of the `before` and `after` hooks, the JSON reporter captures them, but we dont capture it on the base reporter which is a bug. Now we render the error and also print out the duration it took to run the journeys.

fix: capture hook errors in base reporter

---

__tests__/cli.test.ts
__tests__/core/runner.test.ts
__tests__/fixtures/params-error.journey.ts
__tests__/index.test.ts
src/cli.ts
src/common_types.ts
src/core/index.ts
src/core/runner.ts
src/dsl/journey.ts
src/helpers.ts

+ Exposes the suite params and params passed via `--config` flag to all our hooks `before, beforeAll, after, afterAll`
+ Params in hooks cannot be modified, throws error otherwise - added a test in `cli.test.ts`. 
+ Follow up of the config support PR #271

feat: expose params in all hooks

---

__tests__/cli.test.ts
src/cli.ts
src/common_types.ts
src/core/runner.ts
src/parse_args.ts

+ fix #289 
+ Mimics the current heartbeat behaviour by introducing the `--rich-events` flag that will enable `Screenshots, Network, Default to JSON reporter`.

feat: add support for rich events flag

---

examples/docker/heartbeat.docker.yml
examples/inline/short.js

+ When the element is null, the returned collection will not be iterable. So we use the single element instead of using the list.

chore: use different selector to pick banner

---

__tests__/cli.test.ts
__tests__/fixtures/example.journey.ts
src/common_types.ts
src/core/runner.ts
src/parse_args.ts

+ fix #292 
+ Allows for a way to pass an variadic args to `--capability` flag that controls the features inside the agent. 
```
npx @elastic/synthetics examples/todos --capability metrics trace --capability filmstrips
```
+ Also deprecated the previous `--trace, --metrics, --filmstrips` flag which are not required anymore and not used by heartbeat currently.

feat: add support for capabilities flag

---

__tests__/cli.test.ts
package-lock.json
package.json
src/cli.ts

+ fix #297 
+ We now deep merge the params passed from both config and suite params and always prioritize suite params over config params when a key is specified in both.

fix: prioritize suite params over config

---

__tests__/core/runner.test.ts
__tests__/index.test.ts
__tests__/reporters/json.test.ts
package-lock.json
package.json
src/common_types.ts
src/core/runner.ts
src/dsl/journey.ts
src/parse_args.ts
src/reporters/json.ts

+ fix #26 
+ Added support for glob pattern matching for both journey name and tags. 
+ Names and tags can be matched with multiple journeys that has the same name and tags spawned across multiple files. 
```
elastic-synthetics examples/todos/* --match 'check*' 
// will match all the journey that has `check` in their name and tags. 
```
This aligns with `RegExp` or glob matching found in major libraries like jest, folio, mocha etc and we don't support variadiac options for name matching as majority of the cases can be solved with a mix of both.
+ Tags matching which is a variadic option meaning you can pass multiple options in the CLI to match a group of journeys.
```ts
// will run the journeys that are tagged with the respective teams in the kibana repo. 
elastic-synthetics <dir> --tags …
```

feat: add filtering by tags and names

---

.eslintrc.js
NOTICE.txt
__tests__/cli.test.ts
__tests__/fixtures/expect.journey.ts
package-lock.json
package.json
src/core/expect.ts
src/index.ts

+ fix #201 
+ Uses the expect library with custom Matcher interface as some of the expect types are implemented by `jest` like Spy and Snapshot matcher. 
+ Types are namespaced under `synthetics` in global to allow `expect.extend` functionality work with Typescript without throwing any typings error.  Look at https://github.com/elastic/synthetics/blob/fa18f519d4d8488d49f5883b04d601f281aabdcc/__tests__/fixtures/expect.journey.ts for more details. 
+ Test coverage is done for both expect library and also for types with extensions.

feat: add expect assertion library

---

src/core/runner.ts

+ The previous performance improvement https://github.com/elastic/synthetics/pull/274/files was undone by another commit while doing the screenshot post processing.

fix: isolate journeys with context

---

__tests__/sdk/trace-metrics.test.ts
src/common_types.ts
src/sdk/trace-metrics.ts

+ As a result of changes here - https://github.com/elastic/beats/pull/26248

chore: use duration.us for trace events

---

__tests__/core/runner.test.ts
src/core/runner.ts
src/reporters/json.ts

+ fix #280 
+ We capture the beforeAll hook errors and any error that happens in any one of the hooks would be captured and all journeys that run on the current invocation will report that error event with `failed` status to be able to captured as part of the Uptime UI. 
+ `afterAll` errors behaves the same - we report them in the stderror logs which will be captured by Heartbeat.

fix: capture beforeAll hook errors

---

__tests__/cli.test.ts
src/cli.ts
src/common_types.ts
src/core/runner.ts
src/parse_args.ts

+ Remove -e flag in favor of NODE_ENV which will behave the same way as the -e flag. 
+ Dynamic config still works the same way and we default to `development` when running suites.

BREAKING CHANGE: remove -e in favor of NODE_ENV

---

__tests__/core/index.test.ts
__tests__/core/runner.test.ts
src/core/runner.ts
src/helpers.ts

+ fix #320 
+ We clear the global screenshot cache once each journey end. We do not need to worry about the parallel execution problem here as our screenshot path contains the process id which would be different for each worker if we end up running journeys in parallel. 
+ This feels much simpler than creating a hash for every journey where we need to pass that hash across every journey context. 
+ Also cleaned up some deprecated API and moved to promise based FS API.

fix: avoid writing duplicate screenshot docs

---

__tests__/cli.test.ts
src/parse_args.ts

+ We now default to spitting out screenshot blocks whenever `--rich-events` flag is enabled which mimicks the heartbeat mode. 
+ fixes #319 - Allow screenshots option to be overridden per heartbeat monitor config. 
+ remove `-j ` flag in favor of using `--reporter`
+ `network` is now moved inside `capability` to match with other tracing, metrics and filmstrip capability.

feat: default to ssblocks for richevents

---

__tests__/cli.test.ts
__tests__/config.test.ts
__tests__/fixtures/pwoptions.journey.ts
__tests__/index.test.ts
examples/todos/advanced.journey.ts
examples/todos/basic.journey.ts
examples/todos/helpers.ts
examples/todos/hooks.journey.ts
examples/todos/package.json
examples/todos/synthetics.config.ts
package.json
src/cli.ts
src/common_types.ts
src/config.ts
src/core/gatherer.ts
src/core/runner.ts
src/index.ts
src/parse_args.ts

+ fixes #171 
+ fixes #169 
+ fixes #299 
+ fixes #198 
+ fixes #209 
+ Exposes all playwright `BrowserLaunch` options and `ContextOptions` through `playwrightOptions` using the `synthetics.config.ts` file. 
+ CLI params that exist today like `--headless` and `--sandbox` takes precedence over the playwrightOptions when launch in non headless mode and such. 
+ There is no validation right now as its mostly an escape hatch and will be added in the future to avoid `recordVideo` and `screenshot` capture as synthetics provides them out of the box. 
**synthetics.config.ts**
```ts
import type { SyntheticsConfig } from '@elastic/synthetics';
const config: SyntheticsConfig = {
playwrightOptions: {
ignoreHTTPSErrors: true,
extraHTTPHeaders: {
"foo": "bar"
},
...devices['Galaxy S9+'],
},
}
export …
```

feat: add browser and context options support

---

.gitignore

While working in VSCode it's nice to be able to customize settings per project, which creates a `.vscode` directory in the root of the repo. It's very convenient to have this file excluded by `.gitignore`

add .vscode directory to .gitignore file

---

__tests__/cli.test.ts
src/helpers.ts

fix: add fallback for terminal w/o utf-8 support

---

src/core/runner.ts
src/helpers.ts

While working on limiting the node version in CI to match the version installed by Heartbeat (#327) we realized that the use of the `fs/promises` API is not compatible with this node version.
This PR removes the `fs/promises` usage and instead exposes part of the fs API wrapped with `util.promisify()` from `src/helpers` and uses that in `src/core/runner`.

wrap fs methods with promisify for node@12 compat

---

__tests__/cli.test.ts
src/parse_args.ts

+ fix #332 
+ `--json` flag was removed unintentionally in this PR https://github.com/elastic/synthetics/commit/8ec94c9382b8d23a6a451d087b4dd3a498d0e3fd#, so we bring that flag back which is still used by heartbeat 7.13.

fix: support --json flag for heartbeat 7.13

---

__tests__/cli.test.ts
__tests__/index.test.ts
src/cli.ts
src/common_types.ts
src/core/runner.ts
src/parse_args.ts
src/reporters/json.ts

+ fix #288 
+ Deprecates `-s, --suite-params` in favor of `-p, --params`, will be removed before GA as heartbeat still uses the `--suite-params` flag.

feat: deprecate 'suiteparams' infavor of 'params'

---

__tests__/e2e/scripts/setup.sh

+ Revert back to the latest snapshot as we tested the E2E for both 7.13.1 and now latest master.

chore: update e2e again to latest snapshot

---

__tests__/cli.test.ts
src/reporters/json.ts

+ fix #339 
+ When device is emulated via playwright options - https://github.com/elastic/synthetics/blob/87d1b9a8cb6fea360a74cd66a4910551059bf3ec/examples/todos/synthetics.config.ts#L8-L21 the underlying screenshot block calculation is in float instead of integers which causes error in sharp. 
+ Instead of trying to use floating points, we fallback to the nearest using `Math.floor' and discard the extra width and height. 
**NOTE: This is a quick fix and in the future we will modify the block construction algorithm to handle all the dynamic device emulation strategies and construct different number of blocks for greater efficiency.**

fix: capture screenshots during device emulation

---

package.json

+ fix errors that will be thrown when using different version of node on the local environment. 
From Kibana
```
info [bazel] error @elastic/synthetics@1.0.0-beta.8: The engine "node" is incompatible with this module. Expected version "12.18.4". Got "14.17.2"
```
+ CI still runs with the version of `12.18.4` as per `.nvmrc` file.

fix: remove the node version restriction

---

__tests__/dsl/journey.test.ts
src/core/index.ts
src/dsl/journey.ts

+ Id and Name are always required for the monitor to show correctly in the Uptime UI.

fix: default to name for journey id

---

examples/e-commerce/demo.journey.js

+ Updates the e-commerce demo to load all the lazy loaded contents as most of the content is asynchronously loaded and we need to wait until the network requests are complete to keep the screenshots of the step meaningful.

chore: update demo to load content

---

__tests__/core/runner.test.ts
src/core/runner.ts

+ When there are iframes and new windows that exists as part of the page lifecycle, we capture the wrong page URL as we are using the page object from previous session. 
+ part of #253

fix: capture correct url for navigations

---

__tests__/core/runner.test.ts
src/cli.ts
src/core/runner.ts

+ part of #253 
+ captures proper screenshots for new navigations done via popups and new tabs.
+ Listens for `page` events in each step and captures the screenshot of last navigation that happened in the step. 
```js
step('Popup Landing Page', async () => {
await page.goto(`http://localhost:8080/popup1.html`);
await page.waitForSelector('text=Test popup page 1');
});
step('Open Popup', async () => {
const [popup] = await Promise.all([
page.waitForEvent('popup'),
page.click('#linkWithPopup'),
]);
// Test 2 - new tab (not new popup window)
await Promise.all([
context.waitForEvent('page'),
page.click('#linkWithPopupNoNewWindow'),
]);
});
```

fix: record correct screenshots for popups

---

__tests__/cli.test.ts
__tests__/index.test.ts
src/cli.ts
src/common_types.ts
src/parse_args.ts

Fixes https://github.com/elastic/synthetics/issues/356
Accomplishes the fix by making --rich-events always exit with a code of 0, even if tests fail

Add --quiet-exit-code and make it default --rich-events behavior

---

__tests__/cli.test.ts
src/cli.ts
src/common_types.ts
src/core/runner.ts
src/parse_args.ts

+ fix #335 
+ Remove `--json`, `--network`, '--suite-params'. These flags are not used by HB and we have alternates in place like `--reporter=json`, `--rich-events`, `--params`.

BREAKING CHANGES: drop support for heartbeat 7.13

---

__tests__/cli.test.ts
src/cli.ts

This also refactors the CLIMock in the cli tests to use a builder pattern to make injecting stdin nicer.

Add `expect` to injected vars in inline scripts.

---

__tests__/formatter/__snapshots__/javascript.test.ts.snap
__tests__/formatter/javascript.test.ts
src/formatter/javascript.ts

+ Paves the way for consuming IR in the future and allows recorder to use the module directly from here instead of keeping the code at various places. 
+ Synthetics generator is based on the code generator interface implementation of Playwright JavaScript formatter. Kept mostly in sync to make sure we can switch to PW format in the future. 
+ Handles both inline and scripted journeys based on a simple flag. 
**Note: Only exception is the use of assertion IR which is different from PW actions which does not have the capability yet.**

feat: add synthetics script generator

---

__tests__/cli.test.ts
src/cli.ts
src/common_types.ts
src/parse_args.ts

Heartbeat 7.15/7.x did not get https://github.com/elastic/beats/pull/26674 backported to them. Since they will be released soon we need to work on re-supporting the `--suite-params` flag and do a new release once this is merged.

Re-add support for suite params

---

__tests__/core/gatherer.test.ts
__tests__/core/runner.test.ts
src/core/gatherer.ts

Fixes https://github.com/elastic/synthetics/issues/232
Appends Elastic/Synthetics to UA string. 
This PR uses a pretty ugly way to determin current user agent string and append the desired string into it.
Not sure if there is a way better way to do this. Struggling with playwright docs on how to get the current user agent string without opening a browser context.

Append Elastic/synthetics to UA string

---

__tests__/reporters/json.test.ts
src/core/runner.ts
src/helpers.ts

Starting in Node 16, recursive fs.rmdir calls are deprecated and will log a
warning.  It's recommended to use fs.rm intead.
https://nodejs.org/api/deprecations.html#DEP0147
Kibana currently exits on process warnings, this will look like:
```
✓  Step: 'Navigates to details page' succeeded (72 ms)
(node:663222) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
Node.js process-warning detected:
DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
at emitRecursiveRmdirWarning (node:internal/fs/utils:816:13)
at …
```

chore: Use rm instead of rmdir for recursive operations

---

__tests__/formatter/__snapshots__/javascript.test.ts.snap
__tests__/formatter/javascript.test.ts
src/formatter/javascript.ts

+ For the recorded use case, when step action is edited and IR is sent over to the formatter, we need to preserve the edited title instead of generating a new one.

chore: use action title if available in context

---

__tests__/cli.test.ts
__tests__/fixtures/example.journey.ts
src/parse_args.ts

+ fix #386 
+ As part of `--rich-events` flag, all trace level data will be sent as `step/metrics` events to HB.

feat: enable trace as part of rich-events

---

__tests__/cli.test.ts
__tests__/core/gatherer.test.ts
src/helpers.ts
src/parse_args.ts

Fixes https://github.com/elastic/synthetics/issues/284
Fixes the default network throttling to Mbps

fix: fix megabytes to mbps

---

__tests__/reporters/base.test.ts
__tests__/reporters/json.test.ts
__tests__/reporters/junit.test.ts
src/core/gatherer.ts
src/core/runner.ts
src/reporters/json.ts

+ fix #409 
Heartbeat monitor calculation is based on the event.timestamp field for journey start and journey end event. Synthetic agent journey/end timestamp is calculated after post processing of the screenshots and network events being written to the JSON output. As a result, Step duration and Monitor duration timings would be hugely different as we are accounting for all the CPU heavy work that comes to extracting and chopping screenshots. 
We use the timestamp during journey end and don't account for the time taken for the post processing of other work that synthetics agent is doing under the hood.

fix: end timestamp should reflect duration

---

__tests__/cli.test.ts
src/cli.ts
src/common_types.ts
src/parse_args.ts

+ We have reverted this change - https://github.com/elastic/synthetics/pull/379 for the time being to make 7.15 work, But we added patch to the 7.x branch to add params support in HB and now that we are at the 7.16 release timeline, we can safely remove this from Synthetics side.

deprecate suite-params option over params

---

.ci/Jenkinsfile

Stash the `.nvm` folder is causing the following error, so let's do not doit because is not needed:
```
[2021-11-10T23:49:49.429Z] java.nio.file.NoSuchFileException: /var/lib/jenkins/workspace/nt-rum_elastic-synthetics_PR-405/.nvm/versions/node/v14.17.5/lib/node_modules/npm/bin/npm-cli.js
[2021-11-10T23:49:49.429Z] 	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
[2021-11-10T23:49:49.429Z] 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
[2021-11-10T23:49:49.429Z] 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
[2021-11-10T23:49:49.429Z] 	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
[2021-11-10T23:49:49.429Z] 	at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSyste …
```

fix: do not stash `.nvm` folder

---

.ci/e2e-synthetics.groovy
.ci/jobs/e2e-synthetics-mbp.yml
.ci/jobs/e2e-synthetics-schedule.yml
.ci/schedule.groovy

Create the JJBB definition (aka the Jenkins UI jobs) for:
- The scheduling twice a day as requested
- The e2e pipeline.
Create the e2e pipeline skeleton, the implementation for what to run to be done in a follow up.
It was requested to create a scheduled execution of the new E2E twice a day and notify in slack the outcome.
I decided to enable a Multibranch Pipeline to be able to test the pipeline manually if needed on a PR basis. It will only be triggered automatically on a daily basis (twice).
In my experience, Multibranch Pipelines help to iterate faster since we can work on a PR basis.
https://github.com/elastic/synthetics/pull/417 and https://github.com/elastic/synthetics/pull/393

[jjbb] for scheduling e2e jobs

---

.ci/Jenkinsfile

Use `withNodejsEnv` to simplify the `nvm` and `nodejs` installation steps
Uses https://github.com/elastic/apm-pipeline-library/pull/1402

ci: use withNodejsEnv step

---

src/index.ts

As part of https://github.com/elastic/synthetics-recorder/issues/85, it would be good to depend on the upstream action type instead of maintaining parallel types that might be out of sync. It will take some of the maintenance burden off of the recorder as well.
With this change, when the next release is published we should be able to reference this type and delete our existing action type.

Export `ActionInContext` type

---

__tests__/e2e/scripts/ci_integration.sh

The e2e pipeline has been failing for a few days. It has been failing because the image downloaded for elastic agent complete was ```docker.elastic.co/beats/elastic-agent-complete:8.0.0-52f8db06-SNAPSHOT``` but the cleanup process try to remove ```docker.elastic.co/beats/elastic-agent-complete:8.0.0-SNAPSHOT``` causing then a failure on the pipeline
Following @kuisathaverat recommendation the ```|| echo "FAILED"``` is being added in the cleanup in order to ignore the error. In CI this is not a problem since the agents are ephemeral.

chore: prevent docker rmi to fail when removing image

---

__tests__/e2e/scripts/test_versions.sh
__tests__/e2e/versions

The synthetics E2E [pipeline](https://apm-ci.elastic.co/job/apm-agent-rum/job/e2e-synthetics-mbp/job/master/63/console) is failing when executing tests for 8.1.0-SNAPSHOT due to an unhealthy container: ERROR: for elastic-agent Container "dada48cb7ab1" is unhealthy.
The reason of this issue is visible in the logs of that container:
`Kibana Fleet setup failed: http POST request to http://kibana:5601/api/fleet/setup fails: Unauthorized: <nil>. Response: {"statusCode":401,"error":"Unauthorized","message":"Unauthorized"}`
Issue where the agent team is working on a fix: elastic/beats#29603
Having the E2E pipeline repeatedly is not good psychologically speaking that's why is being disabled. Once the fix in the agent is done we will enable it again.
That's why this …

chore: exclude 8.1.0-SNAPSHOT from CI

---

.ci/e2e-synthetics.groovy

Prevents notifications in slack and email when fleet/agent/synthetics e2e tests are successful

chore - prevent notification of successful e2e tests

---

__tests__/e2e/scripts/test_versions.sh
__tests__/e2e/versions

The [PR](https://github.com/elastic/beats/pull/29651) with the updates in the agent has been already merged. Because of that we can enable again the 8.1.0-SNAPSHOT in the E2E test pipeline.
That snapshot has been excluded since the following PR: https://github.com/elastic/synthetics/pull/433

chore: enable 8.1.0-SNAPSHOT

---

__tests__/core/gatherer.test.ts
src/core/gatherer.ts

> ⚠️ There is more E2E test information [here](https://github.com/elastic/beats/issues/29495#issuecomment-1011068200) in case you'd like to use the Heartbeat image built from source.
This PR contributes to elastic/beats#29681 as it makes the `synthetics` runner work with the `ubuntu` images we will use.
After this PR, the Heartbeat container should be able to execute the `synthetics` runner.
The Heartbeat container wasn't able to run `synthetics` to completion, as the runner would hang indefinitely.
It couldn't do so because it didn't have the necessary graphics library ([`mesagl`](https://www.mesa3d.org/)) available to make hardware acceleration work ([more specifically, it seems Chromium uses `osmesa` for off-screen rendering](https://docs.mesa3d.org/osmesa.html)) and `newPage` not to …

Stop runner from hanging indefinitely within ubuntu docker images [elastic/beats#29681]

---

src/formatter/javascript.ts

As part of the work for https://github.com/elastic/synthetics-recorder/issues/85, these additional fields are required.
They're part of Playwright's output objects, and while they're not used in Synthetics we do use them downstream in the recorder.
Both fields added as optional, should be no measurable impact.

chore: Add missing fields for action/context types

---

__tests__/cli.test.ts
src/cli.ts

+ For inline journeys, the ReferenceErrors inside script was not captured as part of the journey error context. This PR fixes that behaviour and also adds tests. 
+ The issue was due to the fact that our inline journey function was `async`, which is wrong as the JourneyCallback is expected to register steps synchronously.

fix: capture ReferenceError inside journeys

---

__tests__/core/gatherer.test.ts
src/core/gatherer.ts

+ When users are overriding the useragent with  `--playwright-options` the UA was being overwritten in the agent code. This PR fixes that by using the UA passed to the agent.

fix: allow UA emulation when overriding

---

__tests__/e2e/package.json
__tests__/e2e/synthetics.journey.ts

Adds an inline browser monitor to test to Synthetics e2e tests.
This test is intended to replace the flaky test skipped here: https://github.com/elastic/synthetics/blob/main/__tests__/core/runner.test.ts#L701

feat: add inline e2e test for real world page

---

__tests__/core/gatherer.test.ts
package-lock.json
package.json
src/core/gatherer.ts
src/reporters/json.ts

+ uses `browser.connect(wsendpoint, {})` instead of the old deprecated API
+ Updated dependencies to the latest version to prepare the update for PW sooner.

update deprecated apis and dependencies

---

__tests__/helper.test.ts
package-lock.json
package.json
src/cli.ts
src/common_types.ts
src/core/index.ts
src/dsl/journey.ts
src/dsl/step.ts
src/helpers.ts
src/index.ts
tsconfig.json

+ Part of #470 
+ Adds `Location` metadata to the Journey and Step DSL which can be used for formatting the error location and pinpointing to the exact source on the test files. Location metadata is not used anywhere as it lays the foundation for pushing journeys to the monitor management. Will be used in the subsequent PR's. 
+ Sourcemap data was broken due to the discrepancies between `ts-node` which we use to transpile the journey files on the fly and the `source-map-support` library as both were looking in different places for the original source-maps. `ts-node` moved to a forked version of the library. More details here - https://github.com/cspotcode/node-source-map-support/issues/24

feat: location info for journey and step

---

CONTRIBUTING.md

I tried to publish a release and accidentally followed the outdated manual instructions, which are no longer necessary now that there's an automated process.
Deleting these docs to prevent someone else from making the same mistake as me.

docs: Remove manual release instructions

---

__tests__/e2e/synthetics.journey.ts

Elastic Synthetics e2e tests
--
Adjusts the logic for selecting the agent policy in Fleet.
Previously, the HTML element was a `select`. Now it's a custom `EuiSuperSelect`. Instead of using `page.select`, we use `page.click`.

fix: adjust select agent policy selectors

---

__tests__/cli.test.ts
__tests__/fixtures/example.journey.ts
__tests__/plugins/network.test.ts

+ fix #430 
Synthetics runner uses streams in object mode to write the data to the corresponding File descriptor, in our case it's process.stdout. So the runner writes the data on each new line for every event type - `journey/start`, `step/end` and so on.
The data written to the underlying stream will be flushed once their internal buffer length exceeds, We can control this [buffering](https://nodejs.org/api/stream.html#buffering) behavior of streams by using `highWaterMark` option. In the tests case, some of the data is interleaved as screenshot blob data events chunk exceeds that limit and written as interleaved chunks to the file descriptor. 
Our current code does not take this in to account and instead pushes the broken data chunk to the final buffer. The solution was simply to move …

chore: fix flaky tests in CLI mock

---

__tests__/plugins/network.test.ts

+ fix https://github.com/elastic/uptime/issues/460
+ The issue itself was fixed by moving to the network events from PW instead of CDP logic #488
+ Added test case now for timings for the cached resource check. 
1. Create inline journey with the example given on the issue.
```js
step("My Page", async () => {
await page.goto('https://paulb-elastic.github.io/testPageWithCounter.html');
await page.waitForSelector('#counter >> text=Seconds since page loaded: 2');
});
step("Cached version of My Page", async () => {
await page.goto('https://paulb-elastic.github.io/testPageWithCounter.html');
await page.waitForSelector('#counter >> text=Seconds since page loaded: 2');
});
```
2. Run the synthetics CLI from local and ensure the timing data is correct
```
cat examples/inline/example.js | node …
```

chore: add test for cached res timings

---

__tests__/plugins/network.test.ts

+ The previous logic is sometimes flaky when run on CI, so we check for absolute values to make sure the we are not seeing absurd values for cached resources.

chore: fix flaky cache resource test

---

__tests__/cli.test.ts
__tests__/core/runner.test.ts
__tests__/options.test.ts
src/cli.ts
src/common_types.ts
src/core/gatherer.ts
src/core/index.ts
src/core/runner.ts
src/dsl/journey.ts
src/dsl/monitor.ts
src/helpers.ts
src/index.ts
src/options.ts

+ Part of #470
+ Expose the new Monitor DSL that will be used alongside `journey, step` which can be used to configure the monitor settings/configuration before uploading via the `push` command.
+ Instead of exposing it through the callback arguments which we agreed on earlier, `monitor` API sits similar to `journey/step` level which improves the DX by allowing users to set the configuration across all journeys or via file level if we decide to change it in future. 
- Allows for future extensibility to tune it based on file - depending on which file the `monitor.use` API is called, the journeys sits inside those files will get those defaults.
- Extensible that allows the configuration to be exposed via `journey.use`. 
```ts
import { journey, step, monitor } from '@elastic/synthetics';
// …
```

feat: introduce monitor DSL

---

__tests__/e2e/synthetics.journey.ts

elastic-package was recently updated to include pre-existing Uptime data.
To continue supporting our tests, the script will first search for the monitor it's looking for to easily identify the target monitor.

chore: adjust e2e tests to search for monitor before checking for data

---

.ci/e2e-synthetics.groovy
__tests__/e2e/scripts/setup_integration.sh

Currently, Kibana is failing to start for Fleet e2e tests. See the issue encapsulated here. https://github.com/elastic/uptime-dev/issues/99
This PR does two things
1. Pulls logs from Fleet Server, Elastic Agent, and Kibana in the event that `elastic-package stack up` exits with status 1
2. Temporarily disables alerts for these tests

chore: e2e tests - pull logs from docker containers when unhealthy and temporarily disable alerts

---

__tests__/core/runner.test.ts
__tests__/fixtures/example.journey.ts
__tests__/options.test.ts
__tests__/push/__snapshots__/plugin.test.ts.snap
__tests__/push/__snapshots__/request.test.ts.snap
__tests__/push/bundler.test.ts
__tests__/push/index.test.ts
__tests__/push/mock-server.ts
__tests__/push/monitor.test.ts
__tests__/push/plugin.test.ts
__tests__/push/request.test.ts
examples/todos/package.json
package-lock.json
package.json
src/cli.ts
src/common_types.ts
src/core/runner.ts
src/dsl/journey.ts
src/dsl/monitor.ts
src/helpers.ts
src/loader.ts
src/options.ts
src/push/bundler.ts
src/push/index.ts
src/push/monitor.ts
src/push/plugin.ts
src/push/request.ts

+ Part of #470 
+ Adds the subcommand `push` to the Synthetics CLI that would do the following
- Goes over each journey file and bundles that particular journey along with relevant files that are imported by the particular journey
- Creates a archived file for each journeys maintaining the local path (to help with Stack traces when invoked via HB)
- creates a base 64 encoded content that would be sent to Kibana as part of the `MonitorSchema`. 
+ Introduce required options `--url` and `--auth` to the CLI flags that lets user specify the `Kibana URL endpoint` and also the `authentication` details. User auth accepts `username:pass` or `encoded` strings, If the auth parameter is not encoded, they would be encoded by the Synthetics agent before communicating with Kibana. 
+ In order to reduce …

feat: bundle and push all journeys to kibana

---

__tests__/cli.test.ts
__tests__/plugins/network.test.ts
__tests__/push/bundler.test.ts

+ Fix this error when reload didnt trigger on time for cached requests when testing via browser service.  
```
● network › cached resource timings
response.allHeaders: Browser has been closed
184 |     this._addBarrier(
185 |       page,
> 186 |       response.allHeaders().then(resHeaders => {
|                ^
187 |         networkEntry.response.headers = resHeaders;
188 |
189 |         const contentType = resHeaders['content-type'];
```
+ Write file using async instead of stream as we have to deal with when stream has started writing and then have to read otherwise the file wont be present.

chore: fix flaky test with browser close

---

.eslintignore
__tests__/cli.test.ts
__tests__/generator/index.test.ts
__tests__/utils/test-config.ts
package.json
src/cli.ts
src/generator/index.ts
src/generator/utils.ts
src/helpers.ts
templates/.gitignore
templates/journeys/example.journey.ts
templates/journeys/todos.journey.ts
templates/synthetics.config.ts

+ part of #470 
+ Add a new scaffolding command called `init` to the CLI. 
+ `npx @elastic/synthetics init <project-dir>` - You would get everything set up from running tests locally to pushing monitors to the Kibana Monitor management. After scaffolding, the users could do 
- `npm run test ` - Runs the synthetics tests locally
- `npm run push` - Pushes the local journeys with configured monitor values to the uptime monitor management UI.

feat: scaffold a synthetics node project

---

__tests__/push/__snapshots__/request.test.ts.snap
__tests__/push/request.test.ts
src/push/index.ts
src/push/request.ts

+ Part of #470 
+ Handle cases when invalid Kibana endpoint was provided. Most likely happens when development when there is more chance of base path being different between every restart.

chore: handle 404 erorrs on push endpoint

---

README.md
__tests__/utils/test-config.ts

+ With the way our CLI tests run and screenshot being written to the stdout when the reporter is `json` - breaking on new lines might not be always correct as sometimes the underlying stream explicitly buffers everything till a specific length. 
+ So we set screenshots to `off` by default unless the tests are asking to test that functionality explicitly.

chore: set screenshots to off unless enabled

---

__tests__/generator/index.test.ts
src/generator/index.ts
templates/.gitignore
templates/synthetics.config.ts

+ fix #509 
+ We update the `.gitignore` contents if the init is called on an existing directory and override it instead of using it from the templates directory.

fix: write .gitnore files for scaffolding

---

src/cli.ts
src/generator/index.ts
src/push/request.ts

+ fix #511 
+ Sends the push request using the format `Authorization: APiKey <token>` instead of basic auth headers - https://www.elastic.co/guide/en/kibana/master/api-keys.html

feat: use apiKey instead of basic auth

---

__tests__/core/runner.test.ts
__tests__/options.test.ts
__tests__/push/monitor.test.ts
__tests__/utils/test-config.ts
package.json
src/dsl/locations.ts
src/dsl/monitor.ts
src/options.ts
src/push/monitor.ts
utils/update_locations.sh

+ Part of #513 
+ Updates the locations array with new locations list that are part of the global manifest. 
+ Adds a utility script to update the locations from the manifest automatically. Thanks to @andrewvc

feat: update new synthetics test node locations

---

__tests__/core/runner.test.ts
__tests__/generator/index.test.ts
__tests__/options.test.ts
__tests__/push/index.test.ts
__tests__/utils/test-config.ts
package-lock.json
package.json
src/cli.ts
src/generator/index.ts
src/generator/utils.ts
src/options.ts
templates/synthetics.config.ts

+ fix https://github.com/elastic/synthetics-dev/issues/119
+ part of #513 
+ `init` command scaffolding asks interactive questions for both `Locations` and `Schedule` which would be set as default on the Synthetics.config.ts file to be used when pushing the monitors. 
+ Error out when push command is invoked without passing the journey file paths
+ Make the location and schedule option as required `--locations <>` in the CLI and error out when not set. 
+ Allow users to configure the default values via `synthetics.config.ts` file
1. Build the agent `npm run build`
2. Run `node dist/cli.js init test-directory`
3. Verify if it sets up all the default schedule and locations in the `synthetics.config.ts` generated file.

feat: interactive scaffolding for picking default monitor config

---

__tests__/core/gatherer.test.ts
src/core/gatherer.ts

When we originally implemented https://github.com/elastic/synthetics/issues/232 it appears we didn't implement the third AC, allowing users to override our custom UA string "Elastic/Synthetics" which is appended.
Some users need to fully replace the UA, this allows them to do that. Rather than adding a boolean, this assumes that if you're overriding the UA you want full control, which is more in line with the principle of least surprise.
CC @paulb-elastic @drewpost 
PS this is currently a draft because there are no tests, I'll add tests if we agree on this approach.

fix: only append 'Elastic/Synthetics' to default UA

---

templates/.github/workflows/run-synthetics.yml
templates/README.md

+ The old one had couple of copy paste errors as it was referring to the old directory structure.

fix: setup github workflow template correctly

---

__tests__/push/__snapshots__/request.test.ts.snap
__tests__/push/request.test.ts
src/cli.ts
src/common_types.ts
src/push/index.ts
src/push/request.ts

fixes https://github.com/elastic/synthetics/issues/533
Remove --delete option

fix: delete stale monitors by default on push command

---

__tests__/core/runner.test.ts
src/core/runner.ts

+ Playwright by default waits for action timeouts which is set to 30 seconds. So if the user calls `page.go` without explicitly setting timeout, then synthetics agent would wait for that timeout of 30 seconds plus the timeout that the synthetics agent set for the action `page.waitForLoadEvent`. This was a legacy code which was put there to make sure we capture the screenshot after page load for all steps. 
+ The PR addresses the problem by not waiting for the page load as not each step would end up in a load event and we explicitly set a screenshot timeout of 5 seconds. If the agent cannot capture the screenshot within that timeframe, it would end up not writing that document. 
+ Source of this issue is found from the Synthetics service.
1. Use an inline journey
```
step('timeout step', …
```

fix: allow controlling timeouts via actions

---

src/push/request.ts

Remove trailing slash from kibana url option of push command using regex
fixes https://github.com/elastic/synthetics/issues/535

fix: remove trailing slash from kibana host

---

src/push/plugin.ts

Fixes #550 , our custom multi-asset plugin couldn't handle windows paths that start with `C:\` and similar. Switched to FS agnostic code. The errors this caused were somewhat confusing because this only causes `esbuild` to fail later in its process with the message described in #550 .
Should work on linux and windows now.
The easiest way to test this is to use `npx @elastic-synthetics init` to create an example project, then switch to a relative import for synthetics as shown below for `package.json`.
```json
{
"dependencies": {
"@elastic/synthetics": "file:..\\synthetics"
}
}
```
Tested locally on my windows box and WSL linux boxes

Fix for broken win push

---

.ci/jobs/dist-tag-mbp.yml

* Add jjbb jenkins job definition for dist-tag job.
Ref: https://github.com/elastic/observability-robots/issues/1248
Signed-off-by: Adrien Mannocci <adrien.mannocci@elastic.co>

Add jjbb jenkins job definition for dist-tag job

---

__tests__/core/runner.test.ts

+ We have moved away from the async reporter interface, instead we follow the new Reporting API which is synchronous and ensures `journey/end` event is always set. #492

chore: remove elastic.co tests

---

__tests__/core/runner.test.ts
__tests__/push/monitor.test.ts
__tests__/utils/test-config.ts
src/cli.ts
src/common_types.ts
src/core/runner.ts
src/dsl/monitor.ts
src/options.ts
src/push/monitor.ts

Relates to https://github.com/elastic/synthetics/issues/557
If desired, this PR can be tested e2e via the corresponding Kibana PR: https://github.com/elastic/kibana/pull/136777
Enables the ability to define `privateLocations` via the monitor dsl or the `push` command arguments. 
Example usage via `monitor.use`
```
journey('check-if-title-is-present', ({ page, params }) => {
monitor.use({
schedule: 3,
privateLocations: ["YOUR_LOCATION_NAME"],
})
step('launch app', async () => {
await page.goto(params.url);
});
step('assert title', async () => {
const header = await page.$('h1');
expect(await header.textContent()).toBe('todos');
});
});
```
Example usage via command-line.
`npx @elastic/synthetics --url YOUR_KIBANA_URL --project test-project --auth YOUR_AUTH_KEY --schedule 3 --locations …

feat: support private locations in dsl and push command arguments

---

__tests__/fixtures/duplicate.journey.ts
__tests__/push/__snapshots__/index.test.ts.snap
__tests__/push/index.test.ts
src/push/index.ts
src/push/monitor.ts

+ fix #442 
+ Aborts the push command if any of the monitors contain duplicate ids with a clean error message and also linking users to the duplicate monitor files where required. 
+ Decided to handle the logic here as Kibana currently does not have any way to know if there are any duplicates without looking up the saved objects which is not performant when we have all the list already available via the agent. 
- Build the local project using - npm run build
2. Setup a brand new Synthetics project - node dist/cli.js init [optional-dir]
3. Change the monitior ids for some of the monitors. 
4. Run push command - node dist/cli.js push --auth <>

feat: abort push on duplicate monitors

---

__tests__/fixtures/locationinfo.ts
__tests__/generator/index.test.ts
__tests__/locations/index.test.ts
src/generator/index.ts
src/locations/index.ts
src/push/monitor.ts

This PR solves two UX issues
+ Allows the push command to work with Dev and Staging Kibana instances where the location naming scheme might be bit different. `Contitent - Location` to `Location`. 
+ Overrides synthetics project settings and configuration with updated locations when `init` command is run multiple times.
+ Build the project `npm run build`
+ Initialize the new synthetics project - `node dist/cli.js init [dir]`
+ Run init again on the same directory and notice how Synthetics project and config gets updated without asking user override prompts.

chore: override project settings and locations

---

src/cli.ts
src/options.ts

+ fix https://github.com/elastic/synthetics/issues/548
+ Now we have a global common options that would be created shared between different subcommands and can be passed around as well.

fix: allow subcommand to receive common options

---

__tests__/push/bundler.test.ts
src/push/bundler.ts

+ fix #573 
+ With this change, we effectively removed the date property which was set by the zip stream to always refer to the Unix epoch time instead of defaulting to current time in UTC which was causing the zipped contents to be changed everytime when we run push command. 
1. Build the files, `npm run build`
2. Initialize a project - `node dist/cli.js init dir`
3. cd into `dir` and change the synthetics package to link to the current one. `@elastic/synthetics: file:../` in package.json file.
4. Install the synthetics package to link - `npm install`
5. Run the push command - `npm run push`

fix: bundled monitor content must be idempotent

---

__tests__/push/__snapshots__/request.test.ts.snap
__tests__/push/index.test.ts
__tests__/push/request.test.ts
src/push/index.ts
src/push/request.ts

+ fix #565 
+ Creates warnings for the stale monitors if the push succeeded without any failures. If there are errors then these warnings are dropped on the floor to make room for users to fix the errors first before checking the warnings.

fix: add warnings for stale monitors

---

CHANGELOG.md
package-lock.json
package.json
src/push/index.ts
src/push/monitor.ts
src/push/request.ts

Pushes project monitor requests individually, following up with a larger request to account for stale monitors.

fix: push monitor requests individually

---

src/cli.ts
src/generator/index.ts

read auth from `SYNTHETICS_API_KEY` if available

feat: support SYNTHETICS_API_KEY env variable for auth 

---

__tests__/generator/index.test.ts
__tests__/push/__snapshots__/index.test.ts.snap
__tests__/push/index.test.ts
__tests__/push/monitor.test.ts
src/cli.ts
src/common_types.ts
src/config.ts
src/generator/index.ts
src/generator/utils.ts
src/push/index.ts
src/push/monitor.ts
templates/synthetics.config.ts

+ fix #590 
+ Changed the way how the Synthetics agent works with project monitor settings and how we can keep the settings idempotent when users run push on their local dev machine and also on the CI.  Sparked out of discussion here - https://elastic.slack.com/archives/C022SU2U6DC/p1662556348346669
+ As a result, Introduced the project setting in the synthetics.config file instead of having yet another project.json file
There was other way, we could have solved this using the same project.json  and constructing them on demand and still be able to provide the same idempotentcy. But having them on the config file, has tons of advantages right now and also in the future.
- Users can immediately see how the values like id, space and url  values are filled in when they initialize the agent, …

fix: save project settings in synthetics config

---

package-lock.json
package.json

While we are not vulnerable to CVEs in these libs it'd be nice to use newer versions that aren't tracked by security scanners.

Update sharp / undici

---

__tests__/push/__snapshots__/index.test.ts.snap
__tests__/push/index.test.ts
src/push/index.ts
src/push/request.ts

+ fix #581 
+ users would be promoted with a dialog when pushing with empty monitors which then clicking `Yes` would nuke the entire project in Kibana. 
+ Also fixed a bug where we kept pushing even on auth errors, now we immediately exit when we find errors during pushing.

feat: delete entire project via push command

---

__tests__/push/index.test.ts
src/cli.ts
src/common_types.ts
src/push/index.ts

+ fix #601 
+ `npx @elastic/synthetics push --auth <key> -y` would skip the questionnare and forcefully push the project monitors during two phases
- When deleting the entire project
- When project is pushed with different id than pushed before.

feat: support --yes flag to skip and force push

---

src/push/plugin.ts

+ Currently for dev purposes, if we end up creating the Synthetics project as part of the Synthetics agent directory, it would result in locally imported helper files marked as `external` which when run on HB would result in this error. 
```
{
"code": "BAD_CMD_STATUS",
"stack_trace": null,
"type": "io",
"message": "journey did not finish executing, 0 steps ran: command '/tmp/elastic-synthetics-unzip-1725738249/node_modules/.bin/elastic-synthetics /tmp/elastic-synthetics-unzip-1725738249/node_modules/.bin/elastic-synthetics /tmp/elastic-synthetics-unzip-1725738249 --playwright-options {\"headless\":true,\"ignoreHTTPSErrors\":true} --screenshots on --throttling {\"download\":5,\"latency\":20,\"upload\":3} --rich-events --match addition and completion of single task been 2 4 --params \"{1 …
```

chore: check build directory instead of root

---

__tests__/push/monitor.test.ts
src/helpers.ts
src/push/index.ts
src/push/monitor.ts

+ Uses the default schedule from `Synthetics.config.ts` if the schedule is not defined in `heartbeat.yml` files.
+ Warns users about the resolution if the schedule is `< 60 seconds`.

chore: use default schedule and warn for lightweight monitors

---

__tests__/plugins/network.test.ts
src/plugins/network.ts

+ part of #616 
+ Include the transferred header + body size when calculating the transferSize value for a given network request. 
**NOTE: No explicit testing is necessary as there is a dedicated test validating the transferred sizes of the response.**

fix: include header and body for transferSize value

---

__tests__/core/runner.test.ts
__tests__/options.test.ts
__tests__/push/__snapshots__/index.test.ts.snap
__tests__/push/index.test.ts
__tests__/push/monitor.test.ts
src/core/runner.ts
src/dsl/monitor.ts
src/generator/index.ts
src/push/index.ts
src/push/monitor.ts

+ fix #620 
+ PR Adds couple of things to make the schedule validation intact for lightweight and browser monitors. 
+ When users scafolds the project using `init` command, we default to showing the available schedule choices based on the browser schedule instead of defaulting to 10, Keeping the initial value still at 10. 
+ Validates the `synthetics.config.ts` file for schedule if its not using the default available schedules - This helps to prevent users who are already using custom schedules to move towards the available ones once they have upgraded to the new version of the agent. 
+  Improve the typings of the `monitor.use({ schedule: 10 })` to only accept the acceptable browser values. 
+  Throws validation error when users are using any other invalid values that is not part of the …

feat: improve validation for monitor schedules

---

__tests__/push/bundler.test.ts
src/push/plugin.ts

-  fix #625 
- When journey files are pushed, We treat these files differently when bundling 
1. Entry paths - Journey files
2. Imported paths - Other deps / local files imported by the journey files itself. 
- When the journey files are loaded by the bundler, the underlying loader in the `ES build` was defaulting to `JS` which throws error when `Typescript types` are used inside the journey files. This PR fixes the problem by using appropriate loader for the journey files when `push` command is invoked. The test is also added to ensure this does not break in the future. 
1. Build the PR - `npm run build`
2. Create an example journey, `example.journey.ts`
3. Use the example below which relies on TS typings 
```ts
const createJourney = (name: string) => {  // TS types
journey(name, ({ …
```

fix: use correct loader for journey files

---

__tests__/push/__snapshots__/index.test.ts.snap
__tests__/push/index.test.ts
__tests__/utils/server.ts
src/generator/index.ts
src/helpers.ts
src/push/index.ts

+ Takes the user to the monitor management UI where users can see all the pushed monitors
+ Looks like below
1. Build the project - `npm run build`
2. Push a synthetics project - `SYNTHETICS_API_KEY=<> node dist/cli.js push`

feat: show monitor management link once pushed

---

__tests__/push/index.test.ts
src/helpers.ts
src/push/index.ts

+ fix #660 
+ When Kibana NDJSON responses are buffered, this would result in parsing error on the chunking code as buffer length can be different when working on local vs on cloud (proxies).
+ To account for these varying buffer lengths, We consume all the stream body from Kibana as buffers and then parse the NDJSON response to avoid intereleaved parsing errors.

fix: parse buffered NDJSON response from kibana correctly

---

.ci/e2e-synthetics.groovy

Update the go version for synthetics e2e tests

chore - specify go version for e2e tests

---

src/push/kibana_api.ts

`after_key` never becomes null, so we need to check for total.

fix push command get command

---

__tests__/options.test.ts
src/common_types.ts
src/dsl/monitor.ts
src/options.ts

+ fix #689 
+ PR fixes the types and allows throttling to be disabled via
- CLI - `--no-throttling`
- Synthetics Config File - `monitor.throttling: false`
- Monitor API - `monitor.use({ throttling: false })`
+ Needs Kibana fix to work End to End - https://github.com/elastic/kibana/issues/148344

fix: allow disabling throttling in project monitors

---

src/generator/index.ts

+ fix #680 
+ This prompts the user before overwriting the existing `synthetics.config.file`. 
+ For the `package.json` - It will not be overwritten when the init is run multiple times
- `npm init -y` process will skip the package.json installation if there is already a `package.json` file. 
- Our patching logic will only modify the existing file if the `test` or `push` script is not defined. Safe operation.
+ For `.gitignore` - We overwrite only if the `node_modules` or `.synthetics` is not present - Safe operation.

feat: prompt before overriding config file

---

templates/lightweight/heartbeat.yml

The `lightweight.yml` is not being pushed because it’s missing the `heartbeat.monitors:` heading

fix: add monitor heading to lightweight scaffolding template 

---

__tests__/core/gatherer.test.ts
src/common_types.ts
src/core/gatherer.ts

With this we can provide a custom data-test id like `data-test-subj`, will make life easier with kibana tests specifically.

enable use of custom data-test-id

---

package-lock.json
src/push/monitor.ts

+ fix #712 
+ Ignores all the yaml files inside `node_modules` and `.github` directory to be defensive from adding the monitors that are added as templates from the Elastic synthetics source package itself.

fix: ignore yml files inside node_modules dir

---

.eslintignore
__tests__/push/monitor.test.ts
src/dsl/monitor.ts
src/push/monitor.ts
templates/lightweight/heartbeat.yml

add types for status alert
status alert can be enabled/disable using 
```
monitor.use({
schedule: 10,
alert: {
status: {
enabled: false,
},
},
});
```
in lightweight:
```
heartbeat.monitors:
- type: http
name: Todos Lightweight
id: todos-lightweight
enabled: true
urls: "https://elastic.github.io/synthetics-demo/"
schedule: '@every 3m'
timeout: 16s
alert.status.enabled: true
```

add types for status alert

---

.pre-commit-config.yaml
__tests__/plugins/network.test.ts
src/core/gatherer.ts
src/core/index.ts
src/core/logger.ts
src/plugins/network.ts

+ Addition to what we did on #719 
+ Upstream bug in Chrome - https://bugs.chromium.org/p/chromium/issues/detail?id=1427331
+ Avoid Waiting for all network events as its error prone and might hang the tests from getting closed forever when there are upstream bugs in browsers or Playwright. So we log and drop these events once the test run is completed
+ Added a sig int handler to handle uncaught errors when not run in HB mode.

fix: drop network events once test runs to completion

---

__tests__/options.test.ts
src/cli.ts
src/common_types.ts
src/options.ts

+ fix #740 
+ Fixes the issue with not able to run in non headless mode in any environments. Also removes the unused `no-headless` flag that is not required anymore as we can simulate it based on `--playwright-options '{"headless": false}`

fix: use headless value from playwrightOptions

---

__tests__/core/gatherer.test.ts
__tests__/utils/test-config.ts
src/common_types.ts
src/core/gatherer.ts

+ fix #738
+ PR changes the default navigation timeout for all journeys to `50 seconds` instead of `30 seconds`. Same applies to all actions as well which is controlled by `actionTimeout`. 
+ Allow setting the timeouts mainly `navigationTimeout` and `actionTimeout` via the `playwrightOptions` configuration. These are  prioritized over the default timeout of `50 seconds` which is set by the agent.
+ This is backwards compatible meaning, individual method timeouts would still be preferred over both of these timeouts. Ex: `page.go("url", {timeout: 2000})` would be preferred over `playwrightOptions.navigationTimeout` and `default 50 seconds` timeout.

feat: allow setting navigation and action timeouts

---

src/plugins/network.ts

+ We have migrated away from plain CDP `devtools` network events and using PW events, so removing it as its not used.

chore: remove unused network cdp command

---

THROTTLING.md
__tests__/cli.test.ts
__tests__/core/gatherer.test.ts
__tests__/fixtures/synthetics.config.ts
__tests__/options.test.ts
__tests__/push/index.test.ts
docs/throttling.md
src/cli.ts
src/core/gatherer.ts
src/dsl/monitor.ts
src/helpers.ts
src/options.ts
src/push/index.ts

+ fix #756
+ Disables the Network emulation throttling settings via Chrome devtools in the browser CDP session and also provides warnings to the user at different places when users tries
- Run tests locally with `--throttling` flag
- Run tests locally with `--no-throttling` flag
- Push monitors with `--throttling` and `--no-throttling` flag.
- Push monitors with `monitor.use({throttling: {} )` or `monitor.use({throttling: false})`  on journey level. 
- Push monitors when `monitor.use({throttling: {}))` set on file level. 
+ Cleaned up the old throttling formatting code as its not required anymore since we have disabled throttling altogether.

feat: disable throttling and emit warning

---

.github/workflows/release.yml

+ The old Jenkins script was cleaning up manually after `npm install` step which is not required. Also, we cant call `npm run clean` as the dependencies wont be available till the environment is prepared with `npm ci`. Example error - https://github.com/elastic/synthetics/actions/runs/4898079942/jobs/8746832489

chore: fix release gh action script

---

__tests__/formatter/__snapshots__/javascript.test.ts.snap
__tests__/formatter/javascript.test.ts
src/formatter/javascript.ts
src/index.ts

Exports `SyntheticsGenerator` class from top-level core. Works around some export issues with playwright-core so the Synthetics Recorder can access this class.
Also imports tests and types from the recorder.

[Synthetics] Migrate `SyntheticsGenerator` code back to Synthetics

---

__tests__/helper.test.ts
__tests__/push/monitor.test.ts
src/common_types.ts
src/core/runner.ts
src/dsl/journey.ts
src/helpers.ts
src/loader.ts
src/options.ts
src/push/monitor.ts

+ fix #754 
+ PR adds support for `--pattern, --tags, --match` which will be applied while pushing lighweight monitors as well. 
+ Added guards to catch errors that might arise when trying to apply transforms to Lightweight monitor files (.yml).

feat: support pattern, match, tags for pushing lightweight

---

.github/workflows/release.yml
CONTRIBUTING.md
README.md

+ Remove beta and other experimental labels from the repo. 
+ Release script is not correct still, have to use separate tool like `semantic-release` or similar to read it based on our PR commits.

chore: prepare for 1.0 stable release

---

src/index.ts

Right now this type lives in both the Recorder and Synthetics. We want to delete it from the recorder, and to reference it here.
Doing a top-level export will simplify the import path, as right now the Recorder has to:
```typescript
import { FramDescription } from '@elastic/synthetics/src/formatter/javascript';
```

[Chore] Export `FrameDescription` from JavaScript formatter

---

__tests__/push/index.test.ts
__tests__/push/monitor.test.ts
__tests__/utils/kibana-test-server.ts
src/cli.ts
src/common_types.ts
src/helpers.ts
src/push/index.ts
src/push/monitor.ts
src/push/utils.ts

+ fix #725 
+ Add support for pushing params for Lightweight monitors when used in
- Synthetics config file 
- CLI flags `--params {"foo": "bar"}`
+ Added a backwards compatibility check to drop `params` config if the push is performed on stack `<8.7.2`. 
+ Check the changes with Kibana PR - https://github.com/elastic/kibana/pull/157226

feat: support params for lw monitors with push

---

src/generator/index.ts
src/helpers.ts

Fixes: https://github.com/elastic/synthetics/issues/769
We replace uptime URLs with the ones from the synthetics app since the ones from uptime will not be available in 8.8.0
**Screenshot with new URL for generating an API key:**
**Screenshot with new URL to see pushed monitors in Kibana:**

fix: replace uptime urls with the ones from synthetics app

---

src/generator/index.ts

+ fix #768 
+ The underying library gets confused with the index vs the value being passed as initial value. So we correctly use the default schedule now `10` which will be highlighted by the prompt.

fix: use correct schedule when scaffolding projects

---

__tests__/fixtures/synthetics.config.ts
__tests__/options.test.ts
src/cli.ts
src/common_types.ts
src/core/runner.ts
src/options.ts

+ Fixes the issue when applying the screenshot config from `monitor` field in the global `synthetics.config.ts` to all pushed monitors.
+ Added a new mode which merges all the relevant monitor config from the monitor key only during the push command instead of performing extra work during the local runner mode. 
+ `screenshot` is defaulted to `on` only when the tests are executed locally to keep the backwards compatibility as before. But during the push command, we prefer the `--screenshot` flag when its configured and use the `synthetics.config.ts`. Everything can be overriden by `monitor.use` API as before. 
Slack - https://elastic.slack.com/archives/CE4MRBU48/p1686321341637449

fix: use screenshots from synthetics.config file

---

__tests__/plugins/browser-console.test.ts
src/plugins/browser-console.ts

+ fix #721 
+ Playwright added this capability recently, where we can listen to all the browser console events for all pages that are created via the created browser context. We make use of that and create all the events that are of type `warning, error` and report them for failed tests. 
Check this commit for review - https://github.com/elastic/synthetics/pull/784/commits/33a9320a0358f54f76ee29a5602655a037262821

feat: listen to console events in browser context

---

__tests__/fixtures/synthetics.config.ts
__tests__/options.test.ts
__tests__/push/monitor.test.ts
src/common_types.ts
src/dsl/monitor.ts
src/options.ts
src/push/monitor.ts

Support tls alert key
```
heartbeat.monitors:
- type: http
name: Todos Lightweight
id: todos-lightweight
enabled: true
urls: "https://elastic.github.io/synthetics-demo/"
schedule: '@every 3m'
timeout: 16s
alert.status.enabled: true
alert.tls.enabled: true
```

feat: support tls alert key for project monitors

---

__tests__/push/monitor.test.ts
src/push/monitor.ts

Handle alert config in following format as well
```
heartbeat.monitors:
- type: http
name: Todos Lightweight
id: todos-lightweight
enabled: true
urls: "${devUrl}"
schedule: '@every 3m'
timeout: 16s
alert:
status.enabled: false
tls.enabled: false
```
Edit: 
Continuation of https://github.com/elastic/synthetics/pull/785 which is related to [elastic/kibana#159697](https://github.com/elastic/kibana/pull/159697)

fix: handle nested alert keys

---

__tests__/core/runner.test.ts
__tests__/push/__snapshots__/index.test.ts.snap
__tests__/push/index.test.ts
__tests__/push/monitor.test.ts
src/cli.ts
src/common_types.ts
src/core/runner.ts
src/dsl/monitor.ts
src/options.ts
src/push/index.ts
src/push/monitor.ts

+ fix #780
+ fix #787 
+ PR removes the ability to add `--tags`and `--match` to the push command and aborts the command if the command is run with any of the CLI flags.
+ Adds the ability to configure tags for the project based browser and lightweight monitors. Will be overridden by the individual monitor.tags or journey.tags if present on the monitors themselves. 
+ `private_locations` and `privateLocations` are supported in the lightweight monitor config. 
+ `alert.status, alert.tls` was not captured from global config file for browser monitors. Fixed that as well. 
- Build the project `npm run build`
- Run the Push command 
```sh
SYNTHETICS_API_KEY=<key> node dist/cli.js push --tags "foo*"
// aborts and logs the error
```
- Test with configuring `monitor.tags` in the synthetics.config …

fix: remove match/tags from push command

---

package-lock.json
package.json

+ Preparing for some esbuild features and removing `typescript` from the dependencies as we dont use typescript anymore for bundling/transpilation of journeys. `esbuild` is the single tool used during both times. 
1. Run `npm run build`
2. Bundle a test project with some deps and throw a error inside step and verify if sourcemaps are correct.

chore: update esbuild and move ts to dev-deps

---

.gitignore
__tests__/push/monitor.test.ts
src/dsl/journey.ts
src/dsl/monitor.ts
src/push/index.ts
src/push/monitor.ts

fixes https://github.com/elastic/synthetics/issues/802
update hash logic to account for bundling.
Earlier it was doing difference based on hash calculated before bundling,  in updated logic diff will be done after hash calculated based on content of bundle.

fix: update hash logic to account for bundling

---

src/index.ts

+ do all exports from `playwright-chromium` for now. Fixing the #810

chore: export devices from chromium

---

__tests__/options.test.ts
src/cli.ts
src/common_types.ts
src/options.ts

add `--no-headless` cli option
fixes https://github.com/elastic/synthetics/issues/799

feat: add --no-headless cli option

---

__tests__/locations/index.test.ts
src/cli.ts
src/generator/index.ts
src/locations/index.ts
src/options.ts
src/push/index.ts

fixes https://github.com/elastic/synthetics/issues/718
align cli options between push and locations for url/auth !!

fix: align cli options between push and locations for url/auth

---

package-lock.json
package.json
src/common_types.ts
src/push/kibana_api.ts
src/push/utils.ts

Kibana api returns version as string
`"version":{"number":"8.7.1",`

fix: use correct type for kibana version

---

__tests__/utils/kibana-test-server.ts
src/push/kibana_api.ts
src/push/utils.ts

The Agent sends a request to Kibana during `push` operations to check its version number. Unfortunately, the API endpoint responsible for returning this data will always return a `2XX` error code, even if credentials are invalid, [for reasons](https://github.com/elastic/kibana/pull/94287#issuecomment-795643347), essentially because this endpoint acts as a heartbeat for Kibana in certain cases.
We can get around this issue [by calling](https://github.com/elastic/synthetics/pull/821/files#diff-a57766b2528b00ef17f58b293951b9da05293f17b8049cf03201bcddb0b7a7d7L67) `/api/stats` instead of `/api/status`. This endpoint returns the Kibana version and will throw a `401` in the event of a garbage API key, thus solving both problems.
---
**Note:** the rest of the info in the description is kept for …

fix: Throw better error message if version parsing fails

---

__tests__/cli.test.ts
__tests__/fixtures/expect.journey.ts
bundles/build.js
bundles/package-lock.json
bundles/package.json
bundles/src/index.js
bundles/src/index.ts
package-lock.json
package.json
src/core/expect.ts
utils/build.js

+ fix [#808 ](https://github.com/elastic/synthetics/issues/700)
+ Bundles the PW test library expect matcher with the synthetics and replaces the expect from jest in favor of the PW test matchers. 
+ The PR uses the `expect` library from the `@playwright/test` without bringing in the full runner which we do not require as we have our own Synthetics runner which is build with different syntax. This also replaces the `expect` from jest in favor of the PW test matchers which under the hood is built on top of expect.
+ With bundling approach, we get the benefit of only importing the necessary modules from the PW test and core and still utilize all the available matchers except for the matchers that does comparision on the files - `toMatchSnapshot` and `toHaveScreenshot`. 
+ [ ] Update the …

feat: bundle expect from @playwright/test library

---

.github/actions/setup-totp/action.yml

The action does not have access to the `secrets` context.
This change fixes the error and uses the inputs instead, which it was supposed to do in the first place.

ci: fix setup-totp action

---

__tests__/plugins/browser-console.test.ts
src/plugins/browser-console.ts

+ fix https://github.com/elastic/synthetics/issues/815
+ Available from Playwright 1.38.0 - PR updates the PW to the latest version and captures the unhandled rejections via the new `weberror` event from browser contest instead of relying on the page level `pageerror` event which does not provide the rejections across multiple pages.
+ Docs - https://playwright.dev/docs/api/class-weberror

feat: capture unhandled rejections across all pages

---

.github/workflows/e2e.yml

+ E2E tests are failing in main due to elastic-package version dependency - https://github.com/elastic/synthetics/actions/runs/6237678207/job/16931806039

chore: fix e2e test go version

---

__tests__/push/monitor.test.ts
src/common_types.ts
src/push/monitor.ts

+ Addresses the concerns raised on the previous Retest PR - https://github.com/elastic/synthetics/pull/845#discussion_r1346088146
+ Also takes the local override in favor of the global one for lightweight monitors.

feat: camelcase retest config for lightweight monitors

---

src/push/request.ts

align push command timeout with kibana route, kibana default timeout is 120s. 
this addresses part of https://github.com/elastic/synthetics/issues/851

fix: align push command timeout with kibana route

---

.github/workflows/release.yml

Apparently, workflow_dispatch inputs are not actually booleans but are strings. When running the release.yml manually with default inputs the GitHub Action will not run as expected and skip some steps:
See https://github.com/actions/runner/issues/1483

chore(ci): use string evaluation rather than boolean

---

.github/workflows/release.yml

Fix the missing quote and enable this step to run always to help with testing this in this branch
https://github.com/elastic/synthetics/actions/runs/6636911709/job/18030209681 tested this PR.

fix(ci): missing quoting the echo command

---

src/push/monitor.ts
src/push/utils.ts

+ fix #860 
+ PR adds normalization technique that deals with path traversal abusal that would eventually lead to doing lookups while encoding bundled journeys when pushing project based browser monitors.

fix: normalize monitor names when bundling

---

package-lock.json
package.json

+ This was slipped when we did the change last time during the PW upgrade - https://github.com/elastic/synthetics/commit/f75c4705b30f30a2b33b2d20e82b18a65adfa0e6
+ Fixing it so we dont need to do anything separate in the Recorder - https://github.com/elastic/synthetics-recorder/pull/480

chore: keep pw version same as other pw deps

---

src/push/request.ts

Kibana will reject external requests to `internal` routes by default in Serverless.
We flag our requests as `internal` by passing the `x-elastic-internal-origin` header with requests. This patch includes this header in the requests we send to Kibana, which will allow us to query the project monitor API without making it a documented public API.

feat: introduce kibana interal origin header for serverless requests

---

__tests__/reporters/__snapshots__/buildkite-cli.test.ts.snap
__tests__/reporters/buildkite-cli.test.ts
src/index.ts
src/reporters/base.ts
src/reporters/build_kite_cli.ts
src/reporters/index.ts

feat:  buildkite bare minimun cli reporter

---

package-lock.json
package.json

+ Update babel deps to keep it up to date. 
+ Also updates `follow-redirects` package.

chore(deps): override follow-redirect and update babel deps

---

src/push/bundler.ts

+ As a interim solution, Increase the recommended bundle size limit to 1500Kb from 800kb. We will look in to minification and other sorts of optimization techniques as a separate step.

feat: double monitor bundle size to 1500Kb

---

src/push/bundler.ts

+ Fix that was Incorrectly pushed to set the size at 200kb.

fix: keep size limit at 1500kb for project monitors

---

__tests__/push/bundler.test.ts
package-lock.json
package.json
src/core/transform.ts
src/push/bundler.ts

+ fix #883 
+ Updated esbuild to latest `0.19.11` to work with certain modules. 
+ Minifying the bundles turned out to not yield significant savings than minifying just the whitespaces and also required more work on the runner side when reconstructing the source for running the journeys. Wrote detailed information on the original issue - https://github.com/elastic/synthetics/issues/883#issuecomment-1885918654

feat: minify whitespaces when bundling monitors

---

.github/workflows/dist-tag.yml

We have agreed to use this approach:
> Given the name of the package never changes and I dont expect it to change anytime in the future. We can replace the value of the .name with @elastic/synthetics since the release is specific to the synthetics package.
This will help with solving the issue defined in [here](https://securitylab.github.com/research/github-actions-untrusted-input/#remediation)

ci(github-action): use hardcoded package name

---

.github/workflows/opentelemetry.yml

No need to maintain the static list of GitHub Workflows to be monitored with the CI/CD Observability using Opentelemetry

ci(github-action): use wildcards for discovering all the workflows

---

__tests__/core/runner.test.ts
src/common_types.ts
src/core/runner.ts
src/push/monitor.ts

+ fix #894 
+ enabled: false and retestOnFailure: false on the synthetics global config did not get passed to Kibana which effectively meant the users can only enable/disable them via individual monitor config. This PR fixes the problem and allows all monitors to be overridden with correct value.

fix: allow overriding enabled/retestOnFailure via global config

---

.github/workflows/ci.yml
.github/workflows/dist-tag.yml
.github/workflows/e2e.yml
.github/workflows/pr-title-lint.yml
.github/workflows/test-reporter.yml

⚠️ This PR was created by an automated tool. Please review the changes carefully. ⚠️ 
We want to set the default permissions for workflows to read-only for contents. 
This is a security measure to prevent accidental changes to the repository.
This change adds a top-level permissions block to all workflows in the .github/workflows directory.
```yaml
permissions:
contents: read
```
In some cases workflows might need more permissions than just `contents: read`.
Please checkout this branch and add the necessary permissions to the workflows.
If your workflow uses a Personal Access Token (PAT), we can still add the permissions block,
but it will not have any effect.
Merging this PR as is might cause workflows that need more permissions to fail.
If there are any questions, please reach out to …

ci: add permissions block to workflows

---

__tests__/push/monitor.test.ts
src/push/monitor.ts

+ fix #888 
+ YAML anchors help with DIY principle when same multiple monitors have similar structure. When users are maintaining a large number of monitors, this becomes super handy.

feat: support yml anchors during push command

---

__tests__/reporters/json.test.ts
src/reporters/json.ts

+ fix #468 
+ Redacts some of the well known sensitive headers and other Access token related keys that might be accidentally captured by the agent when capturing network information. 
+ Cookies are already filtered out by Playwright, But we still get rid of Cookie and Set cookie for the request/response cycle to be on safer side.

fix: redact sensitive req/response headers by default

---

__tests__/push/index.test.ts
src/cli.ts
src/common_types.ts
src/options.ts
src/push/index.ts

+ Add support for Push command that was not handling the `--config` option correctly. This PR fixed that and allows users to push the same journeys under different projects using different configuration file. 
```
> npx @elastic/synthetics push --config <synthetics.config.prod.ts>
> npx @elastic/synthetics push --config <synthetics.config.qa.ts>
```

feat: add support for --config option in push command

---

__tests__/generator/index.test.ts
src/generator/index.ts
src/options.ts

+ fix https://github.com/elastic/synthetics/issues/906
+ Part of https://github.com/elastic/synthetics/issues/907
+ Adds support for validating both the Kibana URL or cloud.id and adds validation step if the given URL is invalid. 
+ Hides API key on the CLI prompt and adds the API Key to the push command

feat: improve project scaffolding experience

---

__tests__/core/runner.test.ts
__tests__/fixtures/synthetics.config.ts
__tests__/options.test.ts
__tests__/push/__snapshots__/index.test.ts.snap
__tests__/push/index.test.ts
__tests__/push/monitor.test.ts
src/cli.ts
src/common_types.ts
src/core/runner.ts
src/dsl/monitor.ts
src/options.ts
src/push/monitor.ts

+ Part of https://github.com/elastic/synthetics/issues/910
+ Filtering in push via tags/match has been asked a lot both externally and internally as it makes it easier for the users to control the monitors getting pushed to Kibana. We have [intentionally made the decision](https://github.com/elastic/synthetics/issues/780) to not support it, mainly because monitors were deleted behind the scenes when users pushed monitors with different tags. We [improved deletion flow](https://github.com/elastic/synthetics/pull/912) and requires explicit approval from the user before all the monitors gets deleted, Also the monitors deleted are shown to the user if `DEBUG=synthetics` flag is enabled. 
+ PR adds support for filtering monitors via `--tags and --match` CLI flags in addition to the …

feat: support tags/match filtering in push

---

src/push/request.ts

+ fix #920 
+ Underlying error was triggered from Undici HTTP client when we consume the Response body twice during the error scenario, This hides the error message and throws the default TypeError instead. Copying docs from undici
```
Note: Once a mixin has been called then the body cannot be reused, thus calling additional mixins on .body, e.g. .body.json(); .body.text() will result in an error TypeError: unusable being thrown and returned through the Promise rejection.
```

fix: avoid consuming kibana response twice

---

package.json

+ We introduced provenance https://github.com/elastic/synthetics/pull/919 during the publishing phase which fails with validation error - https://github.com/elastic/synthetics/actions/runs/8942914195/job/24566505353
```
npm ERR! 422 Unprocessable Entity - PUT https://registry.npmjs.org/@elastic%2fsynthetics - Error verifying sigstore provenance bundle: Failed to validate repository information: package.json: "repository.url" is "", expected to match "https://github.com/elastic/synthetics" from provenance
```

chore: fix provenance validation error

---

src/core/runner.ts
src/plugins/tracing.ts
src/sdk/trace-processor.ts

+ Sometimes the page gets crashed during the screenshot events, making it really hard to debug whats happening with the Journey/Steps. This is fixed already in the PW v1.45 - https://github.com/microsoft/playwright/issues/28995#issuecomment-2167261979. PR just adds a debug log event when screenshot fails to get captured for some reason and makes it easier to see whats happening during page crash events.

fix: log screenshot errors in debug mode

---

__tests__/push/index.test.ts
src/push/index.ts
src/push/kibana_api.ts

Adds an environment variable to configure chunk size when pushing monitors to Kibana.
1. Create a test project
2. Check out this PR. Run `npm install` then `npm run build`.
3. Run npm link
4. Check out the directory for the test project
5. run npm link @elastic/synthetics
6. Run `CHUNK_SIZE=1 SYNTHETICS_API_KEY=MXhmQURwRUI1UGtRakt5TW5zWk46VWtFTWJrbE9RMjZTdFBrRVpFd190Zw== npm run push`
7. Watch as only 1 monitor is pushed at a time

feat: support configurable chunk size

---

__tests__/e2e/scripts/setup.sh
package-lock.json
package.json

Update sharp to 0.33 to install to use npm-provided native dependencies: https://github.com/lovell/sharp/issues/3750.
Additionaly, update min supported node engine to 18.20.3, matching stack versions: ttps://github.com/elastic/beats/pull/40038.

chore: update sharp to 0.33

---

.github/workflows/release.yml

Due to the introduction of tag rulesets, the github-actions[bot] cannot bypass the rule and thus cannot push a tag.
Hence, we use @obltmachine, who is on the bypasser list, to create the release.

ci: use obltmachine for tagging and creating the release in the release workflow

---

.github/workflows/test-reporter.yml

This can be updated and re-enabled since https://github.com/elastic/synthetics/pull/950 and https://github.com/elastic/synthetics/pull/951

ci: update test-reporter workflow

---

.github/workflows/pr-title-lint.yml

We enabled this to validate the PR listing in the title always.
However, I cannot think of what's the reason we cannot protect ourselves and use `Require approval for all outside collaborators` as we do in the other workflows.
Any genuine reasons, we need to run always regardless the code is not tested until the PR has been approved?

ci: use pull-request event

---

src/push/index.ts

+ fix #968
+ Location will be `empty` when setting just the privateLocations property.

fix: ignore missing location on cert check

---

__tests__/cli.test.ts
src/cli.ts
src/core/mfa.ts

+ Part of https://github.com/elastic/synthetics-dev/issues/367
+ Goes together with https://github.com/elastic/synthetics/pull/957 and makes the onboarding to the MFA based auth easier. 
+ Introduces a `totp` command that lets users generate a OTP token based on the provided secret that can be used to onboard the Synthetics TOTP generator to other providers. 
```ts
npx @elastic/synthetics totp secret --issuer <issuer> --label <label>
// prints
OTP Token: 123456
```
Documentation will be covered as part of https://github.com/elastic/observability-docs/issues/4334

feat: introduce totp command for OTP token

---

package-lock.json
package.json
src/push/monitor.ts

+ fixes #976 
Added warnings to npx push for scenarios where monitors are silently ignored.  See #976

fix: adding warning when pushing monitors from yaml files

---

src/index.ts

export types from playwright-core  !!
Tested a simple journey 
```
import { journey, step, monitor, request } from '@elastic/synthetics';
journey(`My Example Journey playwrgiht`, ({ page }) => {
monitor.use({
locations: ['us_central'],
enabled: false,
});
step('launch application', async () => {
const context = await request.newContext();
await page.goto('http://google.com');
});
});
```

feat: export types from playwright-core 

---

__tests__/core/index.test.ts
__tests__/core/runner.test.ts
src/core/index.ts
src/core/runner.ts

+ Some libraries depend on this private variables, so renaming it to the previous value to make things easier.

fix: expose running journey as currentJourney

---

__tests__/push/bundler.test.ts
__tests__/push/monitor.test.ts
package-lock.json
package.json
src/core/globals.ts
src/core/logger.ts
src/dsl/monitor.ts
src/push/bundler.ts
src/push/index.ts
src/push/monitor.ts
src/push/run-local.ts
src/push/utils.ts

+ fix https://github.com/elastic/synthetics/issues/973 and https://github.com/elastic/synthetics/issues/929
+ Setting `DEBUG=synthetics` will provides detailed information like Monitor size, overall project size and monitors that were added/deleted/updated etc. 
+ With `--dry-run`, we have the ability to now run these monitors similar to how it would be run inside the Synthetics Public/Private managed locations.

feat: run pushed monitors locally in dry-run mode

---

src/config.ts

When `synthetics.config.ts` throws an error, `config.ts` doesn't give any clue about the root cause, it's better if we can print the original thrown `Error`.

chore: print error when parsing synthetics.config.ts

---

__tests__/core/runner.test.ts
__tests__/fixtures/synthetics.config.ts
__tests__/options.test.ts
__tests__/push/monitor.test.ts
src/core/runner.ts

Fields were not being added via local config for browser monitors !!
reported via https://discuss.elastic.co/t/monitor-fields-ignored-for-browser-monitors-and-monitor-tags-are-not-merged/374559

fix: add fields for browser monitors via config !!

---

.github/dependabot.yml

Add npm ecosystem.
Remove reviewers, it's not supported anymore. 
There are some examples of how other teams use it:
- https://github.com/elastic/apm-agent-nodejs/blob/main/.github/dependabot.yml

chore: dependabot: add npm
