elastic/synthetics

CONTRIBUTING.md, README.md, examples/docker/run-build-local.sh, examples/todos/README.md
+ Add minimal docs for readme, contributing.md and examples
/cc @bmorelli25
=> update readme and add contributing.md

.ci/Jenkinsfile, .pre-commit-config.yaml, CONTRIBUTING.md, examples/docker/bash-build-local.sh, examples/docker/bash.sh, examples/docker/pull-latest.sh, examples/docker/run-build-local.sh, examples/docker/run.sh
- Add pre-commit
- Fix linted defects from https://github.com/koalaman/shellcheck/
- Use shebang with `#!/usr/bin/env bash`
- Update the contributions with the pre-commit
- UI test output for the pre-commit linting
=> Fix linted shellcheck defects

__tests__/cli.test.ts
+ fix #139 
+ Added tests for few flags that can be passed via CLI
=> chore: add functional CLI tests

CHANGELOG.md
+ Document changelog for each versions moving forward
=> chore: add changelog moving forward

__tests__/plugins/tracing.test.ts
+ fix #214 
+ close all open file handle and close the browser session correctly.
=> chore: fix filmstrip tracer test

README.md
=> [CI] add badge

.ci/Jenkinsfile
Use https://github.com/elastic/apm-pipeline-library/pull/976 to simplify the body manipulation
Need a the above-mentioned PR and also a release
=> ci: use the releaseNotification step

package-lock.json
+ missed from last deps update
=> chore: fix lockfile version

__tests__/e2e/uptime.journey.ts
+ Increasing the timeout for e2e test which always fails during the release job - https://apm-ci.elastic.co/job/apm-agent-rum/job/elastic-synthetics/job/master/138/console
=> chore: increase e2e test timeout

CHANGELOG.md
+ Changelog for the new release `v0.0.1-alpha10`
=> docs: update changelog for alpha.10

CHANGELOG.md
+ https://github.com/elastic/synthetics/releases/tag/v0.0.1-alpha.11
=> docs: add release notes for alpha.11

__tests__/plugins/network.test.ts, src/common_types.ts, src/plugins/network.ts
+ fix #220 
+ `Network` event would be populated with `resourceSize` and `transferSize` values.
=> feat: capture resource and transfer size

package-lock.json, package.json
+ part of #61 
+ Keeping it updated to be released as part of beta.
=> chore: update playwright to latest

CHANGELOG.md
+ Releases notes for alpha 13 and 14.
=> docs: release notes for alpha 13, 14

.ci/Jenkinsfile, CHANGELOG.md, CONTRIBUTING.md
+ Beta release has been done, updated necessary docs changes.
=> docs: beta release changes

examples/todos/package.json
+ only use major versions and beta going forward
=> chore: update todos to use beta

__tests__/plugins/network.test.ts, src/plugins/network.ts
=> fix: exclude data uri from network events

CHANGELOG.md
+ For release https://github.com/elastic/synthetics/releases/tag/v1.0.0-beta.1
=> docs: update release notes for 1.0.0-beta.1

package-lock.json, package.json
=> chore: cleanup unused dependencies

CHANGELOG.md
+ Release notes for v.1.0.0-beta.2
=> docs: release notes for beta 2

CHANGELOG.md
+ Rendered - https://github.com/vigneshshanmugam/synthetics/blob/3cedc408931ce05e0a83e64a626cd590441d80a2/CHANGELOG.md#v100-beta3-2021-06-15
=> docs: release notes for 1.0.0-beta.3

examples/todos/basic.journey.ts, examples/todos/helpers.ts
+ use out own `expect` functionality instead of `assert`.
=> chore: use expect in todos example

CHANGELOG.md
+ Another release before 7.14 - v1.0.0-beta.4
=> docs: release notes for 1.0.0-beta.4

package-lock.json, package.json
+ updates to latest playwright
=> chore: update playwright to 1.12.3

examples/todos/package.json
=> chore: use latest beta in todos

__tests__/cli.test.ts, __tests__/e2e/scripts/setup.sh, src/parse_args.ts
+ Since we don't have a good compatibility matrix for now, let's keep all the old flags and do it after feature freeze - tracked here #335 . 
+ fix #334
=> fix: keep support for heartbeat 7.13.x

examples/e-commerce/.npmrc, examples/e-commerce/README.md, examples/e-commerce/demo.journey.js, examples/e-commerce/package.json, examples/e-commerce/synthetics.config.js, examples/todos/basic.journey.ts, examples/todos/helpers.ts
+ Adds Synthetics tests for E-Commerce demo application
=> chore: add e-commerce demo app

CHANGELOG.md
=> docs: release notes for beta.10

CHANGELOG.md
+ release notes for https://github.com/elastic/synthetics/releases/tag/v1.0.0-beta.11
=> docs: release notes for beta.11

package-lock.json
Make `npm audit` happy. No real vulns for us here.
=> Bump insecure deps

jest.config.js
+  https://github.com/elastic/observability-robots/discussions/710#discussioncomment-1154618
=> chore: increase jest timeout to 15 secs

__tests__/e2e/docker-compose.yml, __tests__/plugins/browser-console.test.ts, package-lock.json, package.json
+ Updates to the latest PW before 7.15.
=> chore: update pw version 1.14.0

__tests__/reporters/__snapshots__/json.test.ts.snap, package-lock.json, package.json
=> chore: update deps before release

CHANGELOG.md
=> docs: release notes for beta.12

__tests__/e2e/uptime.journey.ts
+ Status api has been modified which resulted in build timing out for all E2E tests
=> chore: fix hanging e2e tests

CHANGELOG.md
+ https://github.com/elastic/synthetics/releases/tag/v1.0.0-beta.13
=> docs: release notes for beta.13

CHANGELOG.md
=> docs: release notes for beta.17

examples/e-commerce/demo.journey.js, examples/e-commerce/synthetics.config.js
----
We are modifying the link to the demo application since the previous one is not working as it should
=> Modify demo application link

.ci/e2e-synthetics.groovy
To make sure the images can be pulled from the registry
=> chore: log in into the registry before running the tests

__tests__/cli.test.ts, src/cli.ts
Fixes #407.
After this PR, the runner will _not_ try to read `synthetics.config.[t|j]s` files unless it's given a `--config` parameter.
Furthermore, it allows `config` files which use TypeScript to be read when running `inline` tests. Before, it wasn't possible to read `.ts` configuration files for inline tests, which is what initially caused #407.
**⭐  Please read [this comment](https://github.com/elastic/synthetics/issues/407) for an explanation about why this bug happened, why I've allowed the configuration parameter to be passed for `inline` tests, and about how I've fixed reading `.ts` configs in inline tests.**
Please follow all the test cases below.
1. Checkout this branch and build it (`npm run build`).
2. Create an inline journey like the one below. Save it to …
=> Fix do not read configuration files for inline journeys unless a --config parameter is passed

.ci/Jenkinsfile, .ci/jobs/e2e-synthetics-mbp.yml, .ci/jobs/e2e-synthetics-schedule.yml, .ci/jobs/synthetic-monitoring.yml, .ci/schedule.groovy, CONTRIBUTING.md, README.md, __tests__/e2e/README.md
Neutral naming
Requires https://github.com/elastic/elastic-package/pull/652
=> chore: neutral naming for synthetics

CHANGELOG.md
+ Changelog update for beta.19 and beta.18 (missed last time)
=> docs: release notes for beta.19

CHANGELOG.md
+ Release notes for `v1.0.0-beta.20`
=> docs: release notes for beta.20

CHANGELOG.md
+ Release notes https://github.com/elastic/synthetics/releases/tag/v1.0.0-beta.23
=> docs: release notes for beta.23

__tests__/core/runner.test.ts, __tests__/plugins/tracing.test.ts
=> chore: fix flaky trace events test

CHANGELOG.md
+ Release notes for `v1.0.0-beta.25`
=> docs: release notes for beta.25

__tests__/cli.test.ts, src/cli.ts, src/options.ts
+ fix #516 
+ Honor playwright options via the CLI and config and prefer the individual options over the other two.
=> fix: allow overriding flags with playwright options

CHANGELOG.md
+ Release notes for beta 27 and beta 26
=> docs: release notes for beta-27 & 26

package-lock.json, package.json
+ fix https://github.com/elastic/synthetics/security/dependabot/14
=> chore: upgrade sharp version to avoid vulnerability

src/generator/index.ts
+ fix #513 
+ Point learn more section to the new docs being worked on - https://www.elastic.co/guide/en/observability/current/synthetic-run-tests.html
=> chore: update banner doc in scaffolding

__tests__/e2e/scripts/setup.sh
=> chore: update e2e with 8.3.0 snapshot

CHANGELOG.md
=> docs: release notes for  v1.0.0-beta.30

.ci/Jenkinsfile
* Add the ability to tag a stack release as part of the main process.
Signed-off-by: Adrien Mannocci <adrien.mannocci@elastic.co>
=> Add ability to tag a stack release

__tests__/e2e/synthetics.journey.ts
Removes zip url tests for the elastic-agent e2e suite
=> chore - remove zip url tests for e2e suite

CHANGELOG.md
+ Release notes for v1.0.0-beta.33
=> docs: release notes for beta.33

CHANGELOG.md
=> docs: release notes for 1.0.0-beta.34

CHANGELOG.md
+ Release notes for https://github.com/elastic/synthetics/releases/tag/v1.0.0-beta.36
=> docs: release notes for beta.36

.github/dependabot.yml
+ If it gets noisy, we will remove it.
=> chore: create dependabot updates action

.github/dependabot.yml
+ Reverts elastic/synthetics#628
+ Disabling dependabot.
=> Revert "chore: create dependabot updates action"

src/generator/index.ts, templates/lightweight/heartbeat.yml
+ fix the buggy example - https://github.com/elastic/synthetics/pull/650
=> fix: working lightweight monitors with init

__tests__/plugins/network.test.ts
+ This fixes the flaky test with the cached resource timing data. Using a CSS resource and also adjusted the page to wait for the response since the old test did not ensure the timing data was available.
=> chore: fix flaky cache res timing test

__tests__/push/__snapshots__/index.test.ts.snap, __tests__/push/monitor.test.ts, src/dsl/monitor.ts, src/push/monitor.ts
Relates to https://github.com/elastic/kibana/issues/142653
=> feat: consolidate schedule options for project monitors

package-lock.json, package.json
+ Upgrades the `undici` package to the latest version.
=> chore(deps): upgrade undici package

.github/workflows/opentelemetry.yml
Add OpenTelemetry export workflow
- depends on https://github.com/elastic/synthetics/pull/730
- depends on https://github.com/elastic/synthetics/pull/728
=> Add opentelemetry workflow

.github/workflows/e2e.yml
Change notification channel for e2e workflow
=> Change notification channel for e2e workflow

package-lock.json, package.json
=> chore: upgrade all non dev deps to latest

docs/throttling.md
Add details about network throttling changes and latest behaviour
=> Add throttling details

package-lock.json, package.json
This resolves https://github.com/elastic/synthetics-dev/issues/220
=> Bump semver version

.github/workflows/dist-tag.yml
See https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-an-intermediate-environment-variable
=> ci: harden workflow against injection attacks

src/index.ts
Export devices from playwright-core !!
=> feat: export devices from playwright-core

__tests__/plugins/browser-console.test.ts, src/core/runner.ts, src/helpers.ts, src/plugins/browser-console.ts
collect logs for successful journey as well !!
For successful journey we collect last 10 errors, last 5 warns, infos and logs
=> feat: collect logs for successful journey as well

src/core/runner.ts, src/reporters/base.ts, src/reporters/index.ts, src/reporters/json.ts
Fixed dry run mode for base reporter 
fixes https://github.com/elastic/synthetics/issues/745
=> fix: fix dry run for base reporter

.github/workflows/opentelemetry.yml, .github/workflows/pr-title-lint.yml, commitlint.config.js, package-lock.json, package.json
We want to release using semantic release. This change is a preparation to ensure we have conventional commit messages on the main branch.
This change creates a workflow to lint the PR title with commitlint when a PR is opened, changes are pushed, or if the title is edited.
That should be sufficient because we are using squash merges where the PR title is used as commit message.
Tested whilst changing the event type to `pull_request` in https://github.com/elastic/synthetics/actions/runs/6085290115/job/16509016926?pr=828
=> ci: check pr title with commitlint

.github/actions/setup-totp/action.yml
Same as https://github.com/elastic/synthetics/pull/830
Unfortunately, I forgot some occurences.
=> ci: fix setup-totp action pt2

package-lock.json
+ Update leaf dependencies to avoid audit warnings.
=> chore: run npm audit fix for leaf depedencies

__tests__/options.test.ts, src/options.ts
fixes https://github.com/elastic/synthetics/issues/837
fix headless option from config file !!
=> fix: fix headless option from config file

__tests__/push/monitor.test.ts, src/common_types.ts, src/dsl/monitor.ts, src/push/monitor.ts
add retest on failure monitor property !!
=> feat: add retest on failure monitor property

package-lock.json, package.json, src/push/request.ts
+ Regular maintenance update. Updates to the latest undici package and fix types.
=> chore: update undici to latest

__tests__/push/utils.test.ts
+ Missed this with the PR https://github.com/elastic/synthetics/pull/861 as the files were not staged. Adding it to make it complete.
=> chore: add monitor normalization tests

package-lock.json, package.json
+ We need to do a patch version bump after the PW mismatch fix to make the release workflow trigger correctly.
=> fix: upgrade deps to trigger a patch release

__tests__/push/monitor.test.ts, src/push/monitor.ts
=> fix: push disabled lightweight monitor correctly

src/push/index.ts
+ fix https://github.com/elastic/synthetics/issues/803
+ fix https://github.com/elastic/synthetics/issues/778
+ Logs the deleted monitors when debug flag is enabled and Promps confirmation dialog when running in TTY mode. 
```sh
DEBUG=synthetics SYNTHETICS_API_KEY=foo npx @elastic/synthetics push
```
=> feat: improve 'push' command monitors delete flow

src/cli.ts, src/options.ts
+ Following some of the changes here - https://github.com/elastic/observability-docs/pull/3728
+ fix https://github.com/elastic/synthetics/issues/910
=> docs: align cli flags with synthetics docs

.github/workflows/release.yml
Enable provenance with GitHub actions:
- https://github.com/semantic-release/npm?tab=readme-ov-file#npm-provenance
- https://docs.npmjs.com/generating-provenance-statements#about-npm-provenance
=> ci: add provenance

package-lock.json, package.json
+ Updates undici and follow-redirects to the most recent patched versions.
=> fix: update deps undici and follow-redirects

__tests__/push/__snapshots__/index.test.ts.snap, __tests__/push/monitor.test.ts, src/dsl/monitor.ts, src/push/monitor.ts
fixes https://github.com/elastic/synthetics/issues/930
support 10 and s30 seconds intervals for lightweight monitors !!
Some changes were also needed in kibana https://github.com/elastic/kibana/pull/185920
=> feat: support every 10 and 30 seconds intervals for lightweight monitors

.github/workflows/e2e.yml, .github/workflows/release.yml
One step closer to move away from Vault
=> ci: use slack bot secret

__tests__/push/index.test.ts, src/push/index.ts, src/push/utils.ts
=> fix: push only newly created/updated monitors

package-lock.json
Include engine update on package-lock.json and trigger release for sharp update.
=> fix(deps): update engine in package lock and release sharp update

.github/workflows/e2e.yml
follow-up of https://github.com/elastic/synthetics/pull/950
=> ci: e2e.yml migrate upload-artifact and download-artifact to v4

src/core/index.ts, src/core/runner.ts, src/dsl/journey.ts, src/dsl/step.ts
- Fix backwards compatibility to 1.14
=> fix: fix backwards compatibility to 1.14

package-lock.json, package.json
Updating semantic-release to latest supported on Node 18.20
=> chore: synthetics semantic release 22.0

package-lock.json, package.json
Update esbuild to latest release.
=> chore(deps): update esbuild

package-lock.json, package.json
Bump `semantic-release` to 24.2.5
=> chore(deps-dev): bump semantic-release

package-lock.json, package.json
Update esbuild to 0.25.6 minor
=> chore(deps): upgrade esbuild to 0.25.6 minor
